#pragma once

typedef enum {
    #define KEY_NONE 0 // empty/invalid key, not included in enum so it isn't required in switch cases.
    KEY_ESCAPE = 1,
    KEY_LEFT_SHIFT,
    KEY_RIGHT_SHIFT,
    KEY_LEFT_CTRL,
    KEY_RIGHT_CTRL,
    KEY_LEFT_ALT,
    KEY_RIGHT_ALT,
    KEY_BACKSPACE,
    KEY_TAB,
    KEY_ENTER,
    KEY_HOME,
    KEY_INSERT,
    KEY_DELETE,
    KEY_END,
    KEY_PAGE_DOWN,
    KEY_PAGE_UP,
    KEY_NUM_LOCK,
    KEY_LEFT_SUPER,
    KEY_RIGHT_SUPER,
    KEY_CAPS_LOCK,

    KEY_SPACE,
    KEY_APOSTROPHE,
    KEY_LEFT_PAREN,
    KEY_RIGHT_PAREN,
    KEY_PLUS,
    KEY_COMMA,
    KEY_MINUS,
    KEY_GRAVE,
    KEY_PERIOD,
    KEY_SLASH,

    KEY_0,
    KEY_1,
    KEY_2,
    KEY_3,
    KEY_4,
    KEY_5,
    KEY_6,
    KEY_7,
    KEY_8,
    KEY_9,

    KEY_COLON,
    KEY_SEMICOLON,
    KEY_ARROW, // key between shift and z on swedish keyboard
    KEY_EQUAL,


    KEY_A,
    KEY_B,
    KEY_C,
    KEY_D,
    KEY_E,
    KEY_F,
    KEY_G,
    KEY_H,
    KEY_I,
    KEY_J,
    KEY_K,
    KEY_L,
    KEY_M,
    KEY_N,
    KEY_O,
    KEY_P,
    KEY_Q,
    KEY_R,
    KEY_S,
    KEY_T,
    KEY_U,
    KEY_V,
    KEY_W,
    KEY_X,
    KEY_Y,
    KEY_Z,

    KEY_LEFT_BRACKET,
    KEY_BACKSLASH,
    KEY_RIGHT_BRACKET,

    KEY_LEFT_ARROW,
    KEY_RIGHT_ARROW,
    KEY_UP_ARROW,
    KEY_DOWN_ARROW,

    KEY_F1,
    KEY_F2,
    KEY_F3,
    KEY_F4,
    KEY_F5,
    KEY_F6,
    KEY_F7,
    KEY_F8,
    KEY_F9,
    KEY_F10,
    KEY_F11,
    KEY_F12,
    KEY_F13,
    KEY_F14,
    KEY_F15,

    KEY_NUMPAD_0,
    KEY_NUMPAD_1,
    KEY_NUMPAD_2,
    KEY_NUMPAD_3,
    KEY_NUMPAD_4,
    KEY_NUMPAD_5,
    KEY_NUMPAD_6,
    KEY_NUMPAD_7,
    KEY_NUMPAD_8,
    KEY_NUMPAD_9,
    KEY_NUMPAD_COMMA,
    KEY_NUMPAD_SLASH,
    KEY_NUMPAD_ASTERISK,
    KEY_NUMPAD_MINUS,
    KEY_NUMPAD_PLUS,
    KEY_NUMPAD_ENTER,

    #define KEY_MAX (KEY_NUMPAD_ENTER+1)

    KEY_MOD_SHIFT     = 0x1,
    KEY_MOD_ALT       = 0x2,
    KEY_MOD_CAPS_LOCK = 0x4,
    KEY_MOD_CTRL      = 0x8,
    KEY_MOD_SUPER     = 0x10,
    KEY_MOD_NUM_LOCK  = 0x20,
} ELOS_Keycode;
