
/*
    AUTO-GENERATED by /mnt/e/dev/elos/kernel/gen_syscalls.py
*/
    
    
#ifndef ELOS_SYSCALL_INCLUDE
#include "elos/syscalls.h"
#endif // ELOS_SYSCALL_INCLUDE

#ifndef ELOS_SYSCALL_IDS_INCLUDE
#define ELOS_SYSCALL_IDS_INCLUDE
typedef enum {
    _SYS_CAPABILITIES = 0,
    _SYS_REQUEST_CAPABILITIES = 1,
    _SYS_DEBUG_LOG = 2,
    _SYS_HEAP_ALLOCATE = 3,
    _SYS_HEAP_FREE = 4,
    _SYS_HEAP_REALLOCATE = 5,
    _SYS_HEAP_MAP = 6,
    _SYS_DEFAULT_MONITOR = 7,
    _SYS_TICKS_PER_SECOND = 8,
    _SYS_SLEEP_NS = 9,
    _SYS_SERVICE_CREATE = 10,
    _SYS_SERVICE_CONNECT = 11,
    _SYS_SERVICE_SEND = 12,
    _SYS_SERVICE_RECV = 13,
    _SYS_SHARED_MEMORY_CREATE = 14,
    _SYS_SHARED_MEMORY_GRANT = 15,
    _SYS_SHARED_MEMORY_INFO = 16,
    _SYS_REQUEST_USER_EVENT_BUFFER = 17,
    _SYS_EXIT = 18,
    _SYS_DEFAULT_AUDIO = 19,
    _SYS_AUDIO_INFO = 20,
    _SYS_CREATE_AUDIO_BUFFER = 21,
    _SYS_DESTROY_AUDIO_BUFFER = 22,
    _SYS_CREATE_ASYNC_RINGS = 23,
    _SYS_DESTROY_ASYNC_RINGS = 24,
    _SYS_SUBMIT_ASYNC_RING = 25,
    _SYS_WAIT_ASYNC_RING = 26,
} ELOS_SyscallID;
    
#endif // ELOS_SYSCALL_IDS_INCLUDE
    

#ifdef ELOS_SYSCALL_IMPL
#undef ELOS_SYSCALL_IMPL

#define SYSCALL0(ID)              \
    asm volatile (                \
        "syscall"                 \
        : "=a" (rax)              \
        : "a" (ID)                \
        : "rcx", "r11", "memory"  \
    );

#define SYSCALL1(ID, ARG0)        \
    asm volatile (                \
        "syscall"                 \
        : "=a" (rax)              \
        : "a" (ID), "D" (ARG0)    \
        : "rcx", "r11", "memory"  \
    );

#define SYSCALL2(ID, ARG0, ARG1)            \
    asm volatile (                          \
        "syscall"                           \
        : "=a" (rax)                        \
        : "a" (ID), "D" (ARG0), "S" (ARG1)  \
        : "rcx", "r11", "memory"            \
    );
    
#define SYSCALL3(ID, ARG0, ARG1, ARG2)                  \
    asm volatile (                                      \
        "syscall"                                       \
        : "=a" (rax)                                    \
        : "a" (ID), "D" (ARG0), "S" (ARG1), "d" (ARG2)  \
        : "rcx", "r11", "memory"                        \
    )

#define SYSCALL4(ID, ARG0, ARG1, ARG2, ARG3)                       \
    register u64 r10 asm ("r10") = (u64)(ARG3);                    \
    asm volatile (                                                 \
        "syscall"                                                  \
        : "=a" (rax)                                               \
        : "a" (ID), "D" (ARG0), "S" (ARG1), "d" (ARG2), "r" (r10)  \
        : "rcx", "r11", "memory"                                   \
    )

#define SYSCALL5(ID, ARG0, ARG1, ARG2, ARG3, ARG4)                            \
    register u64 r10 asm ("r10") = (u64)(ARG3);                               \
    register u64 r8 asm ("r8") = (u64)(ARG4);                                 \
    asm volatile (                                                            \
        "syscall"                                                             \
        : "=a" (rax)                                                          \
        : "a" (ID), "D" (ARG0), "S" (ARG1), "d" (ARG2), "r" (r10), "r" (r8)   \
        : "rcx", "r11", "memory"                                              \
    )

    void SYS_capabilities(ELOS_Capabilities* capabilities)
{
    int rax;
    SYSCALL1(_SYS_CAPABILITIES, capabilities);
}

void SYS_request_capabilities(ELOS_Capabilities* capabilities)
{
    int rax;
    SYSCALL1(_SYS_REQUEST_CAPABILITIES, capabilities);
}

void SYS_debug_log(const char* text, u32 length)
{
    int rax;
    SYSCALL2(_SYS_DEBUG_LOG, text, length);
}

ELOS_Error SYS_heap_allocate(void** newAddress, u64 size)
{
    ELOS_Error rax;
    SYSCALL2(_SYS_HEAP_ALLOCATE, newAddress, size);
    return rax;
}

ELOS_Error SYS_heap_free(void* oldAddress)
{
    ELOS_Error rax;
    SYSCALL1(_SYS_HEAP_FREE, oldAddress);
    return rax;
}

ELOS_Error SYS_heap_reallocate(void** newAddress, u64 size, void* oldAddress)
{
    ELOS_Error rax;
    SYSCALL3(_SYS_HEAP_REALLOCATE, newAddress, size, oldAddress);
    return rax;
}

ELOS_Error SYS_heap_map(void* virtAddress, u64 size)
{
    ELOS_Error rax;
    SYSCALL2(_SYS_HEAP_MAP, virtAddress, size);
    return rax;
}

ELOS_Error SYS_default_monitor(ELOS_FrameBuffer* frameBuffer)
{
    ELOS_Error rax;
    SYSCALL1(_SYS_DEFAULT_MONITOR, frameBuffer);
    return rax;
}

ELOS_Error SYS_ticks_per_second(u64* tps)
{
    ELOS_Error rax;
    SYSCALL1(_SYS_TICKS_PER_SECOND, tps);
    return rax;
}

void SYS_sleep_ns(u64 nanoseconds)
{
    int rax;
    SYSCALL1(_SYS_SLEEP_NS, nanoseconds);
}

ELOS_Error SYS_service_create(const char* name, ELOS_ServiceEndpoint* endpoint, u64 queueSize)
{
    ELOS_Error rax;
    SYSCALL3(_SYS_SERVICE_CREATE, name, endpoint, queueSize);
    return rax;
}

ELOS_Error SYS_service_connect(const char* name, ELOS_ServiceEndpoint* endpoint, u64 queueSize)
{
    ELOS_Error rax;
    SYSCALL3(_SYS_SERVICE_CONNECT, name, endpoint, queueSize);
    return rax;
}

ELOS_Error SYS_service_send(ELOS_ServiceEndpoint endpoint, const void* data, u64 size)
{
    ELOS_Error rax;
    SYSCALL3(_SYS_SERVICE_SEND, endpoint, data, size);
    return rax;
}

ELOS_Error SYS_service_recv(ELOS_ServiceEndpoint endpoint, ELOS_ServiceEndpoint* senderEndpoint, const void** data, u64* size, u64 timeout_ns)
{
    ELOS_Error rax;
    SYSCALL5(_SYS_SERVICE_RECV, endpoint, senderEndpoint, data, size, timeout_ns);
    return rax;
}

ELOS_Error SYS_shared_memory_create(u64 size, ELOS_SharedMemory* handle)
{
    ELOS_Error rax;
    SYSCALL2(_SYS_SHARED_MEMORY_CREATE, size, handle);
    return rax;
}

ELOS_Error SYS_shared_memory_grant(ELOS_SharedMemory handle, ELOS_ServiceEndpoint endpoint)
{
    ELOS_Error rax;
    SYSCALL2(_SYS_SHARED_MEMORY_GRANT, handle, endpoint);
    return rax;
}

ELOS_Error SYS_shared_memory_info(ELOS_SharedMemory handle, void** buffer, u64* size)
{
    ELOS_Error rax;
    SYSCALL3(_SYS_SHARED_MEMORY_INFO, handle, buffer, size);
    return rax;
}

ELOS_Error SYS_request_user_event_buffer(u32 minimumEvents, ELOS_UserEventBuffer** buffer)
{
    ELOS_Error rax;
    SYSCALL2(_SYS_REQUEST_USER_EVENT_BUFFER, minimumEvents, buffer);
    return rax;
}

void SYS_exit(int exitCode)
{
    int rax;
    SYSCALL1(_SYS_EXIT, exitCode);
}

ELOS_Error SYS_default_audio(ELOS_AudioDevice* device)
{
    ELOS_Error rax;
    SYSCALL1(_SYS_DEFAULT_AUDIO, device);
    return rax;
}

ELOS_Error SYS_audio_info(ELOS_AudioDevice device, ELOS_AudioDeviceInfo* info)
{
    ELOS_Error rax;
    SYSCALL2(_SYS_AUDIO_INFO, device, info);
    return rax;
}

ELOS_Error SYS_create_audio_buffer(ELOS_AudioDevice device, ELOS_AudioFormat* format, u32 bufferSize, ELOS_AudioBuffer** buffer)
{
    ELOS_Error rax;
    SYSCALL4(_SYS_CREATE_AUDIO_BUFFER, device, format, bufferSize, buffer);
    return rax;
}

ELOS_Error SYS_destroy_audio_buffer(ELOS_AudioDevice device, ELOS_AudioBuffer* buffer)
{
    ELOS_Error rax;
    SYSCALL2(_SYS_DESTROY_AUDIO_BUFFER, device, buffer);
    return rax;
}

ELOS_Error SYS_create_async_rings(u32 maxEntries, ELOS_AsyncCreateFlag flags, ELOS_AsyncRequestRing** requestRing, ELOS_AsyncCompletionRing** completionRing)
{
    ELOS_Error rax;
    SYSCALL4(_SYS_CREATE_ASYNC_RINGS, maxEntries, flags, requestRing, completionRing);
    return rax;
}

ELOS_Error SYS_destroy_async_rings(ELOS_AsyncRequestRing* requestRing, ELOS_AsyncCompletionRing* completionRing)
{
    ELOS_Error rax;
    SYSCALL2(_SYS_DESTROY_ASYNC_RINGS, requestRing, completionRing);
    return rax;
}

ELOS_Error SYS_submit_async_ring(ELOS_AsyncRequestRing* requestRing)
{
    ELOS_Error rax;
    SYSCALL1(_SYS_SUBMIT_ASYNC_RING, requestRing);
    return rax;
}

ELOS_Error SYS_wait_async_ring(ELOS_AsyncCompletionRing* completionRing, u64 timeout_ns)
{
    ELOS_Error rax;
    SYSCALL2(_SYS_WAIT_ASYNC_RING, completionRing, timeout_ns);
    return rax;
}


#endif // ELOS_SYSCALL_IMPL
    
#ifdef ELOS_ERROR_STRING_IMPL
#undef ELOS_ERROR_STRING_IMPL
    const char *elos_error(ELOS_Error err) {
    switch (err) {
        case ELOS_OK: return "ELOS_OK";
        case ELOS_ERR_RESERVED: return "ELOS_ERR_RESERVED";
        case ELOS_ERR_UNKNOWN: return "ELOS_ERR_UNKNOWN";
        case ELOS_ERR_INVALID_PARAM: return "ELOS_ERR_INVALID_PARAM";
        case ELOS_ERR_INVALID_SYSCALL: return "ELOS_ERR_INVALID_SYSCALL";
        case ELOS_ERR_CAP_DENIED: return "ELOS_ERR_CAP_DENIED";
        case ELOS_ERR_NOT_FOUND: return "ELOS_ERR_NOT_FOUND";
        case ELOS_ERR_BUSY: return "ELOS_ERR_BUSY";
        case ELOS_ERR_UNSUPPORTED_AUDIO_FORMAT: return "ELOS_ERR_UNSUPPORTED_AUDIO_FORMAT";
        case ELOS_ERR_BUFFER_SIZE_NOT_FRAME_ALIGNED: return "ELOS_ERR_BUFFER_SIZE_NOT_FRAME_ALIGNED";
        case ELOS_ERR_BUFFER_SIZE_TOO_BIG: return "ELOS_ERR_BUFFER_SIZE_TOO_BIG";
        case ELOS_ERR_BUFFER_SIZE_TOO_SMALL: return "ELOS_ERR_BUFFER_SIZE_TOO_SMALL";
        case ELOS_ERR_NO_AUDIO_DEVICE: return "ELOS_ERR_NO_AUDIO_DEVICE";
        default: return "ELOS_UNKNOWN_ERROR";
    }
}
#endif // ELOS_ERROR_STRING_IMPL
    