
/*
    AUTO-GENERATED by /mnt/e/dev/elos/kernel/gen_syscalls.py
*/
    
    
#ifndef ELOS_SYSCALL_INCLUDE
#include "elos/syscalls.h"
#endif // ELOS_SYSCALL_INCLUDE

#ifndef ELOS_SYSCALL_IDS_INCLUDE
#define ELOS_SYSCALL_IDS_INCLUDE
typedef enum {
    _SYS_CAPABILITIES = 0,
    _SYS_REQUEST_CAPABILITIES = 1,
    _SYS_DEBUG_LOG = 2,
    _SYS_HEAP_ALLOCATE = 3,
    _SYS_HEAP_FREE = 4,
    _SYS_HEAP_REALLOCATE = 5,
    _SYS_HEAP_MAP = 6,
    _SYS_HEAP_PROTECT = 7,
    _SYS_DEFAULT_MONITOR = 8,
    _SYS_TICKS_PER_SECOND = 9,
    _SYS_SLEEP_NS = 10,
    _SYS_SERVICE_CREATE = 11,
    _SYS_SERVICE_CONNECT = 12,
    _SYS_SERVICE_SEND = 13,
    _SYS_SERVICE_RECV = 14,
    _SYS_SHARED_MEMORY_CREATE = 15,
    _SYS_SHARED_MEMORY_GRANT = 16,
    _SYS_SHARED_MEMORY_INFO = 17,
    _SYS_REQUEST_USER_EVENT_BUFFER = 18,
    _SYS_EXIT = 19,
    _SYS_DEFAULT_AUDIO = 20,
    _SYS_AUDIO_INFO = 21,
    _SYS_CREATE_AUDIO_BUFFER = 22,
    _SYS_DESTROY_AUDIO_BUFFER = 23,
    _SYS_CREATE_ASYNC_RINGS = 24,
    _SYS_DESTROY_ASYNC_RINGS = 25,
    _SYS_SUBMIT_ASYNC_RING = 26,
    _SYS_WAIT_ASYNC_RING = 27,
} ELOS_SyscallID;
    
#endif // ELOS_SYSCALL_IDS_INCLUDE
    

#ifdef ELOS_SYSCALL_IMPL
#undef ELOS_SYSCALL_IMPL
    void SYS_capabilities(ELOS_Capabilities* capabilities)
{
    int retv;
#if defined(__x86_64__)
register size_t _arg0 asm ("rdi") = (size_t)capabilities;

            asm volatile (
                "syscall"
                : "=a" (retv)
                : "a" (_SYS_CAPABILITIES), "r" (_arg0)
                : "rcx", "r11", "memory"
            );
        #else
register size_t _arg0 asm ("ebx") = (size_t)capabilities;

            asm volatile (
                "int $0x80"
                : "=a" (retv)
                : "a" (_SYS_CAPABILITIES), "r" (_arg0)
                : "memory"
            );
        #endif
}

void SYS_request_capabilities(ELOS_Capabilities* capabilities)
{
    int retv;
#if defined(__x86_64__)
register size_t _arg0 asm ("rdi") = (size_t)capabilities;

            asm volatile (
                "syscall"
                : "=a" (retv)
                : "a" (_SYS_REQUEST_CAPABILITIES), "r" (_arg0)
                : "rcx", "r11", "memory"
            );
        #else
register size_t _arg0 asm ("ebx") = (size_t)capabilities;

            asm volatile (
                "int $0x80"
                : "=a" (retv)
                : "a" (_SYS_REQUEST_CAPABILITIES), "r" (_arg0)
                : "memory"
            );
        #endif
}

void SYS_debug_log(const char* text, u32 length)
{
    int retv;
#if defined(__x86_64__)
register size_t _arg0 asm ("rdi") = (size_t)text;
register size_t _arg1 asm ("rsi") = (size_t)length;

            asm volatile (
                "syscall"
                : "=a" (retv)
                : "a" (_SYS_DEBUG_LOG), "r" (_arg0), "r" (_arg1)
                : "rcx", "r11", "memory"
            );
        #else
register size_t _arg0 asm ("ebx") = (size_t)text;
register size_t _arg1 asm ("ecx") = (size_t)length;

            asm volatile (
                "int $0x80"
                : "=a" (retv)
                : "a" (_SYS_DEBUG_LOG), "r" (_arg0), "r" (_arg1)
                : "memory"
            );
        #endif
}

ELOS_Error SYS_heap_allocate(void** newAddress, size_t size)
{
    ELOS_Error retv;
#if defined(__x86_64__)
register size_t _arg0 asm ("rdi") = (size_t)newAddress;
register size_t _arg1 asm ("rsi") = (size_t)size;

            asm volatile (
                "syscall"
                : "=a" (retv)
                : "a" (_SYS_HEAP_ALLOCATE), "r" (_arg0), "r" (_arg1)
                : "rcx", "r11", "memory"
            );
        #else
register size_t _arg0 asm ("ebx") = (size_t)newAddress;
register size_t _arg1 asm ("ecx") = (size_t)size;

            asm volatile (
                "int $0x80"
                : "=a" (retv)
                : "a" (_SYS_HEAP_ALLOCATE), "r" (_arg0), "r" (_arg1)
                : "memory"
            );
        #endif
    return retv;
}

ELOS_Error SYS_heap_free(void* oldAddress)
{
    ELOS_Error retv;
#if defined(__x86_64__)
register size_t _arg0 asm ("rdi") = (size_t)oldAddress;

            asm volatile (
                "syscall"
                : "=a" (retv)
                : "a" (_SYS_HEAP_FREE), "r" (_arg0)
                : "rcx", "r11", "memory"
            );
        #else
register size_t _arg0 asm ("ebx") = (size_t)oldAddress;

            asm volatile (
                "int $0x80"
                : "=a" (retv)
                : "a" (_SYS_HEAP_FREE), "r" (_arg0)
                : "memory"
            );
        #endif
    return retv;
}

ELOS_Error SYS_heap_reallocate(void** newAddress, size_t size, void* oldAddress)
{
    ELOS_Error retv;
#if defined(__x86_64__)
register size_t _arg0 asm ("rdi") = (size_t)newAddress;
register size_t _arg1 asm ("rsi") = (size_t)size;
register size_t _arg2 asm ("rdx") = (size_t)oldAddress;

            asm volatile (
                "syscall"
                : "=a" (retv)
                : "a" (_SYS_HEAP_REALLOCATE), "r" (_arg0), "r" (_arg1), "r" (_arg2)
                : "rcx", "r11", "memory"
            );
        #else
register size_t _arg0 asm ("ebx") = (size_t)newAddress;
register size_t _arg1 asm ("ecx") = (size_t)size;
register size_t _arg2 asm ("edx") = (size_t)oldAddress;

            asm volatile (
                "int $0x80"
                : "=a" (retv)
                : "a" (_SYS_HEAP_REALLOCATE), "r" (_arg0), "r" (_arg1), "r" (_arg2)
                : "memory"
            );
        #endif
    return retv;
}

ELOS_Error SYS_heap_map(void* virtAddress, size_t size, ELOS_Heap_Protection protection)
{
    ELOS_Error retv;
#if defined(__x86_64__)
register size_t _arg0 asm ("rdi") = (size_t)virtAddress;
register size_t _arg1 asm ("rsi") = (size_t)size;
register size_t _arg2 asm ("rdx") = (size_t)protection;

            asm volatile (
                "syscall"
                : "=a" (retv)
                : "a" (_SYS_HEAP_MAP), "r" (_arg0), "r" (_arg1), "r" (_arg2)
                : "rcx", "r11", "memory"
            );
        #else
register size_t _arg0 asm ("ebx") = (size_t)virtAddress;
register size_t _arg1 asm ("ecx") = (size_t)size;
register size_t _arg2 asm ("edx") = (size_t)protection;

            asm volatile (
                "int $0x80"
                : "=a" (retv)
                : "a" (_SYS_HEAP_MAP), "r" (_arg0), "r" (_arg1), "r" (_arg2)
                : "memory"
            );
        #endif
    return retv;
}

ELOS_Error SYS_heap_protect(void* virtAddress, size_t size, ELOS_Heap_Protection protection)
{
    ELOS_Error retv;
#if defined(__x86_64__)
register size_t _arg0 asm ("rdi") = (size_t)virtAddress;
register size_t _arg1 asm ("rsi") = (size_t)size;
register size_t _arg2 asm ("rdx") = (size_t)protection;

            asm volatile (
                "syscall"
                : "=a" (retv)
                : "a" (_SYS_HEAP_PROTECT), "r" (_arg0), "r" (_arg1), "r" (_arg2)
                : "rcx", "r11", "memory"
            );
        #else
register size_t _arg0 asm ("ebx") = (size_t)virtAddress;
register size_t _arg1 asm ("ecx") = (size_t)size;
register size_t _arg2 asm ("edx") = (size_t)protection;

            asm volatile (
                "int $0x80"
                : "=a" (retv)
                : "a" (_SYS_HEAP_PROTECT), "r" (_arg0), "r" (_arg1), "r" (_arg2)
                : "memory"
            );
        #endif
    return retv;
}

ELOS_Error SYS_default_monitor(ELOS_FrameBuffer* frameBuffer)
{
    ELOS_Error retv;
#if defined(__x86_64__)
register size_t _arg0 asm ("rdi") = (size_t)frameBuffer;

            asm volatile (
                "syscall"
                : "=a" (retv)
                : "a" (_SYS_DEFAULT_MONITOR), "r" (_arg0)
                : "rcx", "r11", "memory"
            );
        #else
register size_t _arg0 asm ("ebx") = (size_t)frameBuffer;

            asm volatile (
                "int $0x80"
                : "=a" (retv)
                : "a" (_SYS_DEFAULT_MONITOR), "r" (_arg0)
                : "memory"
            );
        #endif
    return retv;
}

ELOS_Error SYS_ticks_per_second(u64* tps)
{
    ELOS_Error retv;
#if defined(__x86_64__)
register size_t _arg0 asm ("rdi") = (size_t)tps;

            asm volatile (
                "syscall"
                : "=a" (retv)
                : "a" (_SYS_TICKS_PER_SECOND), "r" (_arg0)
                : "rcx", "r11", "memory"
            );
        #else
register size_t _arg0 asm ("ebx") = (size_t)tps;

            asm volatile (
                "int $0x80"
                : "=a" (retv)
                : "a" (_SYS_TICKS_PER_SECOND), "r" (_arg0)
                : "memory"
            );
        #endif
    return retv;
}

void SYS_sleep_ns(u64 nanoseconds)
{
    int retv;
#if defined(__x86_64__)
register size_t _arg0 asm ("rdi") = (size_t)nanoseconds;

            asm volatile (
                "syscall"
                : "=a" (retv)
                : "a" (_SYS_SLEEP_NS), "r" (_arg0)
                : "rcx", "r11", "memory"
            );
        #else
register size_t _arg0 asm ("ebx") = (size_t)nanoseconds;

            asm volatile (
                "int $0x80"
                : "=a" (retv)
                : "a" (_SYS_SLEEP_NS), "r" (_arg0)
                : "memory"
            );
        #endif
}

ELOS_Error SYS_service_create(const char* name, ELOS_ServiceEndpoint* endpoint, u32 queueSize)
{
    ELOS_Error retv;
#if defined(__x86_64__)
register size_t _arg0 asm ("rdi") = (size_t)name;
register size_t _arg1 asm ("rsi") = (size_t)endpoint;
register size_t _arg2 asm ("rdx") = (size_t)queueSize;

            asm volatile (
                "syscall"
                : "=a" (retv)
                : "a" (_SYS_SERVICE_CREATE), "r" (_arg0), "r" (_arg1), "r" (_arg2)
                : "rcx", "r11", "memory"
            );
        #else
register size_t _arg0 asm ("ebx") = (size_t)name;
register size_t _arg1 asm ("ecx") = (size_t)endpoint;
register size_t _arg2 asm ("edx") = (size_t)queueSize;

            asm volatile (
                "int $0x80"
                : "=a" (retv)
                : "a" (_SYS_SERVICE_CREATE), "r" (_arg0), "r" (_arg1), "r" (_arg2)
                : "memory"
            );
        #endif
    return retv;
}

ELOS_Error SYS_service_connect(const char* name, ELOS_ServiceEndpoint* endpoint, u32 queueSize)
{
    ELOS_Error retv;
#if defined(__x86_64__)
register size_t _arg0 asm ("rdi") = (size_t)name;
register size_t _arg1 asm ("rsi") = (size_t)endpoint;
register size_t _arg2 asm ("rdx") = (size_t)queueSize;

            asm volatile (
                "syscall"
                : "=a" (retv)
                : "a" (_SYS_SERVICE_CONNECT), "r" (_arg0), "r" (_arg1), "r" (_arg2)
                : "rcx", "r11", "memory"
            );
        #else
register size_t _arg0 asm ("ebx") = (size_t)name;
register size_t _arg1 asm ("ecx") = (size_t)endpoint;
register size_t _arg2 asm ("edx") = (size_t)queueSize;

            asm volatile (
                "int $0x80"
                : "=a" (retv)
                : "a" (_SYS_SERVICE_CONNECT), "r" (_arg0), "r" (_arg1), "r" (_arg2)
                : "memory"
            );
        #endif
    return retv;
}

ELOS_Error SYS_service_send(ELOS_ServiceEndpoint endpoint, const void* data, u32 size)
{
    ELOS_Error retv;
#if defined(__x86_64__)
register size_t _arg0 asm ("rdi") = (size_t)endpoint;
register size_t _arg1 asm ("rsi") = (size_t)data;
register size_t _arg2 asm ("rdx") = (size_t)size;

            asm volatile (
                "syscall"
                : "=a" (retv)
                : "a" (_SYS_SERVICE_SEND), "r" (_arg0), "r" (_arg1), "r" (_arg2)
                : "rcx", "r11", "memory"
            );
        #else
register size_t _arg0 asm ("ebx") = (size_t)endpoint;
register size_t _arg1 asm ("ecx") = (size_t)data;
register size_t _arg2 asm ("edx") = (size_t)size;

            asm volatile (
                "int $0x80"
                : "=a" (retv)
                : "a" (_SYS_SERVICE_SEND), "r" (_arg0), "r" (_arg1), "r" (_arg2)
                : "memory"
            );
        #endif
    return retv;
}

ELOS_Error SYS_service_recv(ELOS_ServiceEndpoint endpoint, ELOS_ServiceEndpoint* senderEndpoint, const void** data, u32* size, u64 timeout_ns)
{
    ELOS_Error retv;
#if defined(__x86_64__)
register size_t _arg0 asm ("rdi") = (size_t)endpoint;
register size_t _arg1 asm ("rsi") = (size_t)senderEndpoint;
register size_t _arg2 asm ("rdx") = (size_t)data;
register size_t _arg3 asm ("r10") = (size_t)size;
register size_t _arg4 asm ("r8") = (size_t)timeout_ns;

            asm volatile (
                "syscall"
                : "=a" (retv)
                : "a" (_SYS_SERVICE_RECV), "r" (_arg0), "r" (_arg1), "r" (_arg2), "r" (_arg3), "r" (_arg4)
                : "rcx", "r11", "memory"
            );
        #else
register size_t _arg0 asm ("ebx") = (size_t)endpoint;
register size_t _arg1 asm ("ecx") = (size_t)senderEndpoint;
register size_t _arg2 asm ("edx") = (size_t)data;
register size_t _arg3 asm ("esi") = (size_t)size;
register size_t _arg4 asm ("edi") = (size_t)timeout_ns;

            asm volatile (
                "int $0x80"
                : "=a" (retv)
                : "a" (_SYS_SERVICE_RECV), "r" (_arg0), "r" (_arg1), "r" (_arg2), "r" (_arg3), "r" (_arg4)
                : "memory"
            );
        #endif
    return retv;
}

ELOS_Error SYS_shared_memory_create(size_t size, ELOS_SharedMemory* handle)
{
    ELOS_Error retv;
#if defined(__x86_64__)
register size_t _arg0 asm ("rdi") = (size_t)size;
register size_t _arg1 asm ("rsi") = (size_t)handle;

            asm volatile (
                "syscall"
                : "=a" (retv)
                : "a" (_SYS_SHARED_MEMORY_CREATE), "r" (_arg0), "r" (_arg1)
                : "rcx", "r11", "memory"
            );
        #else
register size_t _arg0 asm ("ebx") = (size_t)size;
register size_t _arg1 asm ("ecx") = (size_t)handle;

            asm volatile (
                "int $0x80"
                : "=a" (retv)
                : "a" (_SYS_SHARED_MEMORY_CREATE), "r" (_arg0), "r" (_arg1)
                : "memory"
            );
        #endif
    return retv;
}

ELOS_Error SYS_shared_memory_grant(ELOS_SharedMemory handle, ELOS_ServiceEndpoint endpoint)
{
    ELOS_Error retv;
#if defined(__x86_64__)
register size_t _arg0 asm ("rdi") = (size_t)handle;
register size_t _arg1 asm ("rsi") = (size_t)endpoint;

            asm volatile (
                "syscall"
                : "=a" (retv)
                : "a" (_SYS_SHARED_MEMORY_GRANT), "r" (_arg0), "r" (_arg1)
                : "rcx", "r11", "memory"
            );
        #else
register size_t _arg0 asm ("ebx") = (size_t)handle;
register size_t _arg1 asm ("ecx") = (size_t)endpoint;

            asm volatile (
                "int $0x80"
                : "=a" (retv)
                : "a" (_SYS_SHARED_MEMORY_GRANT), "r" (_arg0), "r" (_arg1)
                : "memory"
            );
        #endif
    return retv;
}

ELOS_Error SYS_shared_memory_info(ELOS_SharedMemory handle, void** buffer, size_t* size)
{
    ELOS_Error retv;
#if defined(__x86_64__)
register size_t _arg0 asm ("rdi") = (size_t)handle;
register size_t _arg1 asm ("rsi") = (size_t)buffer;
register size_t _arg2 asm ("rdx") = (size_t)size;

            asm volatile (
                "syscall"
                : "=a" (retv)
                : "a" (_SYS_SHARED_MEMORY_INFO), "r" (_arg0), "r" (_arg1), "r" (_arg2)
                : "rcx", "r11", "memory"
            );
        #else
register size_t _arg0 asm ("ebx") = (size_t)handle;
register size_t _arg1 asm ("ecx") = (size_t)buffer;
register size_t _arg2 asm ("edx") = (size_t)size;

            asm volatile (
                "int $0x80"
                : "=a" (retv)
                : "a" (_SYS_SHARED_MEMORY_INFO), "r" (_arg0), "r" (_arg1), "r" (_arg2)
                : "memory"
            );
        #endif
    return retv;
}

ELOS_Error SYS_request_user_event_buffer(u32 minimumEvents, ELOS_UserEventBuffer** buffer)
{
    ELOS_Error retv;
#if defined(__x86_64__)
register size_t _arg0 asm ("rdi") = (size_t)minimumEvents;
register size_t _arg1 asm ("rsi") = (size_t)buffer;

            asm volatile (
                "syscall"
                : "=a" (retv)
                : "a" (_SYS_REQUEST_USER_EVENT_BUFFER), "r" (_arg0), "r" (_arg1)
                : "rcx", "r11", "memory"
            );
        #else
register size_t _arg0 asm ("ebx") = (size_t)minimumEvents;
register size_t _arg1 asm ("ecx") = (size_t)buffer;

            asm volatile (
                "int $0x80"
                : "=a" (retv)
                : "a" (_SYS_REQUEST_USER_EVENT_BUFFER), "r" (_arg0), "r" (_arg1)
                : "memory"
            );
        #endif
    return retv;
}

void SYS_exit(int exitCode)
{
    int retv;
#if defined(__x86_64__)
register size_t _arg0 asm ("rdi") = (size_t)exitCode;

            asm volatile (
                "syscall"
                : "=a" (retv)
                : "a" (_SYS_EXIT), "r" (_arg0)
                : "rcx", "r11", "memory"
            );
        #else
register size_t _arg0 asm ("ebx") = (size_t)exitCode;

            asm volatile (
                "int $0x80"
                : "=a" (retv)
                : "a" (_SYS_EXIT), "r" (_arg0)
                : "memory"
            );
        #endif
}

ELOS_Error SYS_default_audio(ELOS_AudioDevice* device)
{
    ELOS_Error retv;
#if defined(__x86_64__)
register size_t _arg0 asm ("rdi") = (size_t)device;

            asm volatile (
                "syscall"
                : "=a" (retv)
                : "a" (_SYS_DEFAULT_AUDIO), "r" (_arg0)
                : "rcx", "r11", "memory"
            );
        #else
register size_t _arg0 asm ("ebx") = (size_t)device;

            asm volatile (
                "int $0x80"
                : "=a" (retv)
                : "a" (_SYS_DEFAULT_AUDIO), "r" (_arg0)
                : "memory"
            );
        #endif
    return retv;
}

ELOS_Error SYS_audio_info(ELOS_AudioDevice device, ELOS_AudioDeviceInfo* info)
{
    ELOS_Error retv;
#if defined(__x86_64__)
register size_t _arg0 asm ("rdi") = (size_t)device;
register size_t _arg1 asm ("rsi") = (size_t)info;

            asm volatile (
                "syscall"
                : "=a" (retv)
                : "a" (_SYS_AUDIO_INFO), "r" (_arg0), "r" (_arg1)
                : "rcx", "r11", "memory"
            );
        #else
register size_t _arg0 asm ("ebx") = (size_t)device;
register size_t _arg1 asm ("ecx") = (size_t)info;

            asm volatile (
                "int $0x80"
                : "=a" (retv)
                : "a" (_SYS_AUDIO_INFO), "r" (_arg0), "r" (_arg1)
                : "memory"
            );
        #endif
    return retv;
}

ELOS_Error SYS_create_audio_buffer(ELOS_AudioDevice device, ELOS_AudioFormat* format, u32 bufferSize, ELOS_AudioBuffer** buffer)
{
    ELOS_Error retv;
#if defined(__x86_64__)
register size_t _arg0 asm ("rdi") = (size_t)device;
register size_t _arg1 asm ("rsi") = (size_t)format;
register size_t _arg2 asm ("rdx") = (size_t)bufferSize;
register size_t _arg3 asm ("r10") = (size_t)buffer;

            asm volatile (
                "syscall"
                : "=a" (retv)
                : "a" (_SYS_CREATE_AUDIO_BUFFER), "r" (_arg0), "r" (_arg1), "r" (_arg2), "r" (_arg3)
                : "rcx", "r11", "memory"
            );
        #else
register size_t _arg0 asm ("ebx") = (size_t)device;
register size_t _arg1 asm ("ecx") = (size_t)format;
register size_t _arg2 asm ("edx") = (size_t)bufferSize;
register size_t _arg3 asm ("esi") = (size_t)buffer;

            asm volatile (
                "int $0x80"
                : "=a" (retv)
                : "a" (_SYS_CREATE_AUDIO_BUFFER), "r" (_arg0), "r" (_arg1), "r" (_arg2), "r" (_arg3)
                : "memory"
            );
        #endif
    return retv;
}

ELOS_Error SYS_destroy_audio_buffer(ELOS_AudioDevice device, ELOS_AudioBuffer* buffer)
{
    ELOS_Error retv;
#if defined(__x86_64__)
register size_t _arg0 asm ("rdi") = (size_t)device;
register size_t _arg1 asm ("rsi") = (size_t)buffer;

            asm volatile (
                "syscall"
                : "=a" (retv)
                : "a" (_SYS_DESTROY_AUDIO_BUFFER), "r" (_arg0), "r" (_arg1)
                : "rcx", "r11", "memory"
            );
        #else
register size_t _arg0 asm ("ebx") = (size_t)device;
register size_t _arg1 asm ("ecx") = (size_t)buffer;

            asm volatile (
                "int $0x80"
                : "=a" (retv)
                : "a" (_SYS_DESTROY_AUDIO_BUFFER), "r" (_arg0), "r" (_arg1)
                : "memory"
            );
        #endif
    return retv;
}

ELOS_Error SYS_create_async_rings(u32 maxEntries, ELOS_AsyncCreateFlag flags, ELOS_AsyncRequestRing** requestRing, ELOS_AsyncCompletionRing** completionRing)
{
    ELOS_Error retv;
#if defined(__x86_64__)
register size_t _arg0 asm ("rdi") = (size_t)maxEntries;
register size_t _arg1 asm ("rsi") = (size_t)flags;
register size_t _arg2 asm ("rdx") = (size_t)requestRing;
register size_t _arg3 asm ("r10") = (size_t)completionRing;

            asm volatile (
                "syscall"
                : "=a" (retv)
                : "a" (_SYS_CREATE_ASYNC_RINGS), "r" (_arg0), "r" (_arg1), "r" (_arg2), "r" (_arg3)
                : "rcx", "r11", "memory"
            );
        #else
register size_t _arg0 asm ("ebx") = (size_t)maxEntries;
register size_t _arg1 asm ("ecx") = (size_t)flags;
register size_t _arg2 asm ("edx") = (size_t)requestRing;
register size_t _arg3 asm ("esi") = (size_t)completionRing;

            asm volatile (
                "int $0x80"
                : "=a" (retv)
                : "a" (_SYS_CREATE_ASYNC_RINGS), "r" (_arg0), "r" (_arg1), "r" (_arg2), "r" (_arg3)
                : "memory"
            );
        #endif
    return retv;
}

ELOS_Error SYS_destroy_async_rings(ELOS_AsyncRequestRing* requestRing, ELOS_AsyncCompletionRing* completionRing)
{
    ELOS_Error retv;
#if defined(__x86_64__)
register size_t _arg0 asm ("rdi") = (size_t)requestRing;
register size_t _arg1 asm ("rsi") = (size_t)completionRing;

            asm volatile (
                "syscall"
                : "=a" (retv)
                : "a" (_SYS_DESTROY_ASYNC_RINGS), "r" (_arg0), "r" (_arg1)
                : "rcx", "r11", "memory"
            );
        #else
register size_t _arg0 asm ("ebx") = (size_t)requestRing;
register size_t _arg1 asm ("ecx") = (size_t)completionRing;

            asm volatile (
                "int $0x80"
                : "=a" (retv)
                : "a" (_SYS_DESTROY_ASYNC_RINGS), "r" (_arg0), "r" (_arg1)
                : "memory"
            );
        #endif
    return retv;
}

ELOS_Error SYS_submit_async_ring(ELOS_AsyncRequestRing* requestRing)
{
    ELOS_Error retv;
#if defined(__x86_64__)
register size_t _arg0 asm ("rdi") = (size_t)requestRing;

            asm volatile (
                "syscall"
                : "=a" (retv)
                : "a" (_SYS_SUBMIT_ASYNC_RING), "r" (_arg0)
                : "rcx", "r11", "memory"
            );
        #else
register size_t _arg0 asm ("ebx") = (size_t)requestRing;

            asm volatile (
                "int $0x80"
                : "=a" (retv)
                : "a" (_SYS_SUBMIT_ASYNC_RING), "r" (_arg0)
                : "memory"
            );
        #endif
    return retv;
}

ELOS_Error SYS_wait_async_ring(ELOS_AsyncCompletionRing* completionRing, u64 timeout_ns)
{
    ELOS_Error retv;
#if defined(__x86_64__)
register size_t _arg0 asm ("rdi") = (size_t)completionRing;
register size_t _arg1 asm ("rsi") = (size_t)timeout_ns;

            asm volatile (
                "syscall"
                : "=a" (retv)
                : "a" (_SYS_WAIT_ASYNC_RING), "r" (_arg0), "r" (_arg1)
                : "rcx", "r11", "memory"
            );
        #else
register size_t _arg0 asm ("ebx") = (size_t)completionRing;
register size_t _arg1 asm ("ecx") = (size_t)timeout_ns;

            asm volatile (
                "int $0x80"
                : "=a" (retv)
                : "a" (_SYS_WAIT_ASYNC_RING), "r" (_arg0), "r" (_arg1)
                : "memory"
            );
        #endif
    return retv;
}


#endif // ELOS_SYSCALL_IMPL
    
#ifdef ELOS_ERROR_STRING_IMPL
#undef ELOS_ERROR_STRING_IMPL
    const char *elos_error(ELOS_Error err) {
    switch (err) {
        case ELOS_OK: return "ELOS_OK";
        case ELOS_ERR_RESERVED: return "ELOS_ERR_RESERVED";
        case ELOS_ERR_UNKNOWN: return "ELOS_ERR_UNKNOWN";
        case ELOS_ERR_INVALID_PARAM: return "ELOS_ERR_INVALID_PARAM";
        case ELOS_ERR_INVALID_SYSCALL: return "ELOS_ERR_INVALID_SYSCALL";
        case ELOS_ERR_CAP_DENIED: return "ELOS_ERR_CAP_DENIED";
        case ELOS_ERR_NOT_FOUND: return "ELOS_ERR_NOT_FOUND";
        case ELOS_ERR_BUSY: return "ELOS_ERR_BUSY";
        case ELOS_ERR_UNSUPPORTED_AUDIO_FORMAT: return "ELOS_ERR_UNSUPPORTED_AUDIO_FORMAT";
        case ELOS_ERR_BUFFER_SIZE_NOT_FRAME_ALIGNED: return "ELOS_ERR_BUFFER_SIZE_NOT_FRAME_ALIGNED";
        case ELOS_ERR_BUFFER_SIZE_TOO_BIG: return "ELOS_ERR_BUFFER_SIZE_TOO_BIG";
        case ELOS_ERR_BUFFER_SIZE_TOO_SMALL: return "ELOS_ERR_BUFFER_SIZE_TOO_SMALL";
        case ELOS_ERR_NO_AUDIO_DEVICE: return "ELOS_ERR_NO_AUDIO_DEVICE";
        default: return "ELOS_UNKNOWN_ERROR";
    }
}
#endif // ELOS_ERROR_STRING_IMPL
    