
/*
    AUTO-GENERATED by /mnt/e/dev/elos/kernel/gen_syscalls.py
*/
    
#ifndef ELOS_SYSCALL_IDS_INCLUDE
#define ELOS_SYSCALL_IDS_INCLUDE
typedef enum {
    _SYS_CAPABILITIES = 0,
    _SYS_REQUEST_CAPABILITIES = 1,
    _SYS_DEBUG_LOG = 2,
    _SYS_HEAP_ALLOCATE = 3,
    _SYS_HEAP_FREE = 4,
    _SYS_HEAP_REALLOCATE = 5,
    _SYS_HEAP_MAP = 6,
    _SYS_DEFAULT_MONITOR = 7,
    _SYS_TICKS_PER_SECOND = 8,
    _SYS_SLEEP_NS = 9,
    _SYS_SERVICE_CREATE = 10,
    _SYS_SERVICE_CONNECT = 11,
    _SYS_SERVICE_SEND = 12,
    _SYS_SERVICE_RECV = 13,
    _SYS_SHARED_MEMORY_CREATE = 14,
    _SYS_SHARED_MEMORY_GRANT = 15,
    _SYS_SHARED_MEMORY_INFO = 16,
    _SYS_REQUEST_USER_EVENT_BUFFER = 17,
    _SYS_EXIT = 18,
    _SYS_THREAD_EXIT = 19,
    _SYS_SPAWN_THREAD = 20,
    _SYS_JOIN = 21,
    _SYS_SELF = 22,
    _SYS_SPAWN_PROCESS = 23,
    _SYS_DEFAULT_AUDIO = 24,
    _SYS_AUDIO_INFO = 25,
    _SYS_CREATE_BUFFER = 26,
    _SYS_AUDIO_CONTROL = 27,
    _SYS_CREATE_ASYNC_RINGS = 28,
    _SYS_DESTROY_ASYNC_RINGS = 29,
    _SYS_SUBMIT_ASYNC_RING = 30,
    _SYS_WAIT_ASYNC_RING = 31,
} ELOS_SyscallID;
    
#endif // ELOS_SYSCALL_IDS_INCLUDE
    

#ifdef ELOS_SYSCALL_IMPL

#define SYSCALL0(ID)              \
    asm volatile (                \
        "syscall"                 \
        : "=a" (rax)              \
        : "a" (ID)                \
        : "rcx", "r11", "memory"  \
    );

#define SYSCALL1(ID, ARG0)        \
    asm volatile (                \
        "syscall"                 \
        : "=a" (rax)              \
        : "a" (ID), "D" (ARG0)    \
        : "rcx", "r11", "memory"  \
    );

#define SYSCALL2(ID, ARG0, ARG1)            \
    asm volatile (                          \
        "syscall"                           \
        : "=a" (rax)                        \
        : "a" (ID), "D" (ARG0), "S" (ARG1)  \
        : "rcx", "r11", "memory"            \
    );
    
#define SYSCALL3(ID, ARG0, ARG1, ARG2)                  \
    asm volatile (                                      \
        "syscall"                                       \
        : "=a" (rax)                                    \
        : "a" (ID), "D" (ARG0), "S" (ARG1), "d" (ARG2)  \
        : "rcx", "r11", "memory"                        \
    )

#define SYSCALL4(ID, ARG0, ARG1, ARG2, ARG3)                       \
    register u64 r10 asm ("r10") = (u64)(ARG3);                    \
    asm volatile (                                                 \
        "syscall"                                                  \
        : "=a" (rax)                                               \
        : "a" (ID), "D" (ARG0), "S" (ARG1), "d" (ARG2), "r" (r10)  \
        : "rcx", "r11", "memory"                                   \
    )

#define SYSCALL5(ID, ARG0, ARG1, ARG2, ARG3, ARG4)                            \
    register u64 r10 asm ("r10") = (u64)(ARG3);                               \
    register u64 r8 asm ("r8") = (u64)(ARG4);                                 \
    asm volatile (                                                            \
        "syscall"                                                             \
        : "=a" (rax)                                                          \
        : "a" (ID), "D" (ARG0), "S" (ARG1), "d" (ARG2), "r" (r10), "r" (r8)   \
        : "rcx", "r11", "memory"                                              \
    )

    void SYS_capabilities(ELOS_Capabilities* capabilities)
{
    int rax;
    SYSCALL1(_SYS_CAPABILITIES, capabilities);
}

void SYS_request_capabilities(ELOS_Capabilities* capabilities)
{
    int rax;
    SYSCALL1(_SYS_REQUEST_CAPABILITIES, capabilities);
}

void SYS_debug_log(const char* text, u32 length)
{
    int rax;
    SYSCALL2(_SYS_DEBUG_LOG, text, length);
}

ELOS_Error SYS_heap_allocate(void** newAddress, u64 size)
{
    ELOS_Error rax;
    SYSCALL2(_SYS_HEAP_ALLOCATE, newAddress, size);
    return rax;
}

ELOS_Error SYS_heap_free(void* oldAddress)
{
    ELOS_Error rax;
    SYSCALL1(_SYS_HEAP_FREE, oldAddress);
    return rax;
}

ELOS_Error SYS_heap_reallocate(void** newAddress, u64 size, void* oldAddress)
{
    ELOS_Error rax;
    SYSCALL3(_SYS_HEAP_REALLOCATE, newAddress, size, oldAddress);
    return rax;
}

ELOS_Error SYS_heap_map(void* virtAddress, u64 size)
{
    ELOS_Error rax;
    SYSCALL2(_SYS_HEAP_MAP, virtAddress, size);
    return rax;
}

ELOS_Error SYS_default_monitor(ELOS_FrameBuffer* frameBuffer)
{
    ELOS_Error rax;
    SYSCALL1(_SYS_DEFAULT_MONITOR, frameBuffer);
    return rax;
}

ELOS_Error SYS_ticks_per_second(u64* tps)
{
    ELOS_Error rax;
    SYSCALL1(_SYS_TICKS_PER_SECOND, tps);
    return rax;
}

void SYS_sleep_ns(u64 nanoseconds)
{
    int rax;
    SYSCALL1(_SYS_SLEEP_NS, nanoseconds);
}

ELOS_Error SYS_service_create(const char* name, ELOS_ServiceEndpoint* endpoint, u64 queueSize)
{
    ELOS_Error rax;
    SYSCALL3(_SYS_SERVICE_CREATE, name, endpoint, queueSize);
    return rax;
}

ELOS_Error SYS_service_connect(const char* name, ELOS_ServiceEndpoint* endpoint, u64 queueSize)
{
    ELOS_Error rax;
    SYSCALL3(_SYS_SERVICE_CONNECT, name, endpoint, queueSize);
    return rax;
}

ELOS_Error SYS_service_send(ELOS_ServiceEndpoint endpoint, const void* data, u64 size)
{
    ELOS_Error rax;
    SYSCALL3(_SYS_SERVICE_SEND, endpoint, data, size);
    return rax;
}

ELOS_Error SYS_service_recv(ELOS_ServiceEndpoint endpoint, ELOS_ServiceEndpoint* senderEndpoint, const void** data, u64* size, u64 timeout_ns)
{
    ELOS_Error rax;
    SYSCALL5(_SYS_SERVICE_RECV, endpoint, senderEndpoint, data, size, timeout_ns);
    return rax;
}

ELOS_Error SYS_shared_memory_create(u64 size, ELOS_SharedMemory* handle)
{
    ELOS_Error rax;
    SYSCALL2(_SYS_SHARED_MEMORY_CREATE, size, handle);
    return rax;
}

ELOS_Error SYS_shared_memory_grant(ELOS_SharedMemory handle, ELOS_ServiceEndpoint endpoint)
{
    ELOS_Error rax;
    SYSCALL2(_SYS_SHARED_MEMORY_GRANT, handle, endpoint);
    return rax;
}

ELOS_Error SYS_shared_memory_info(ELOS_SharedMemory handle, void** buffer, u64* size)
{
    ELOS_Error rax;
    SYSCALL3(_SYS_SHARED_MEMORY_INFO, handle, buffer, size);
    return rax;
}

ELOS_Error SYS_request_user_event_buffer(u32 minimumEvents, ELOS_UserEventBuffer** buffer)
{
    ELOS_Error rax;
    SYSCALL2(_SYS_REQUEST_USER_EVENT_BUFFER, minimumEvents, buffer);
    return rax;
}

void SYS_exit(int exitCode)
{
    int rax;
    SYSCALL1(_SYS_EXIT, exitCode);
}

void SYS_thread_exit()
{
    int rax;
    SYSCALL0(_SYS_THREAD_EXIT);
}

ELOS_Error SYS_spawn_thread(FN_thread_entry entry, ELOS_ThreadHandle* handle)
{
    ELOS_Error rax;
    SYSCALL2(_SYS_SPAWN_THREAD, entry, handle);
    return rax;
}

ELOS_Error SYS_join(ELOS_ThreadHandle handle)
{
    ELOS_Error rax;
    SYSCALL1(_SYS_JOIN, handle);
    return rax;
}

ELOS_ThreadID SYS_self()
{
    ELOS_ThreadID rax;
    SYSCALL0(_SYS_SELF);
    return rax;
}

ELOS_Error SYS_spawn_process(const char* path, const char* data, u32 data_len)
{
    ELOS_Error rax;
    SYSCALL3(_SYS_SPAWN_PROCESS, path, data, data_len);
    return rax;
}

ELOS_Error SYS_default_audio(ELOS_AudioDevice* device)
{
    ELOS_Error rax;
    SYSCALL1(_SYS_DEFAULT_AUDIO, device);
    return rax;
}

ELOS_Error SYS_audio_info(ELOS_AudioDevice device, ELOS_AudioDeviceInfo* info)
{
    ELOS_Error rax;
    SYSCALL2(_SYS_AUDIO_INFO, device, info);
    return rax;
}

ELOS_Error SYS_create_buffer(ELOS_AudioDevice device, ELOS_AudioFormat* format, u32 bufferSize, ELOS_AudioBuffer** buffer)
{
    ELOS_Error rax;
    SYSCALL4(_SYS_CREATE_BUFFER, device, format, bufferSize, buffer);
    return rax;
}

ELOS_Error SYS_audio_control(ELOS_AudioDevice device, ELOS_AudioOperation operation, size_t value)
{
    ELOS_Error rax;
    SYSCALL3(_SYS_AUDIO_CONTROL, device, operation, value);
    return rax;
}

ELOS_Error SYS_create_async_rings(u32 maxEntries, ELOS_AsyncCreateFlag flags, ELOS_AsyncRequestRing** requestRing, ELOS_AsyncCompletionRing** completionRing)
{
    ELOS_Error rax;
    SYSCALL4(_SYS_CREATE_ASYNC_RINGS, maxEntries, flags, requestRing, completionRing);
    return rax;
}

ELOS_Error SYS_destroy_async_rings(ELOS_AsyncRequestRing* requestRing, ELOS_AsyncCompletionRing* completionRing)
{
    ELOS_Error rax;
    SYSCALL2(_SYS_DESTROY_ASYNC_RINGS, requestRing, completionRing);
    return rax;
}

ELOS_Error SYS_submit_async_ring(ELOS_AsyncRequestRing* requestRing)
{
    ELOS_Error rax;
    SYSCALL1(_SYS_SUBMIT_ASYNC_RING, requestRing);
    return rax;
}

ELOS_Error SYS_wait_async_ring(ELOS_AsyncCompletionRing* completionRing, u64 timeout_ns)
{
    ELOS_Error rax;
    SYSCALL2(_SYS_WAIT_ASYNC_RING, completionRing, timeout_ns);
    return rax;
}


#endif // ELOS_SYSCALL_IMPL
    