#!/usr/bin/env python3

import os, sys, re

ROOT = os.path.dirname(__file__)



prototype_re = re.compile(
    r'([A-Za-z_][A-Za-z0-9_\s\*\t]*?)\s+'
    r'(SYS_[A-Za-z0-9_]+)\s*'
    r'\((.*?)\)\s*;',
    re.S
)

error_re = re.compile(
    r'([A-Za-z_][A-Za-z0-9_\s\*\t]*?)\s+'
    r'(SYS_[A-Za-z0-9_]+)\s*'
    r'\((.*?)\)\s*;',
    re.S
)




def generate_error_string(source):
    match = re.search(
        r'typedef\s+enum\s*\{(.*?)\}\s*ELOS_Error\s*;',
        source,
        re.DOTALL,
    )

    if not match:
        print("\033[31mERROR:\033[0m ELOS_Error enum not found")
        raise ValueError()

    entries = []

    for entry in match.group(1).split(','):
        entry = re.sub(r'/\*.*?\*/', '', entry, flags=re.DOTALL)
        entry = re.sub(r'//.*', '', entry).strip()

        if not entry:
            continue

        m = re.match(
            r'^(ELOS_(?:ERR_[A-Za-z0-9_]+|OK))'
            r'(?:\s*=\s*[^,]+)?$',
            entry,
        )

        if m:
            entries.append(m.group(1))

    out = [
        'const char *elos_error(ELOS_Error err) {',
        '    switch (err) {',
    ]

    for name in entries:
        out.append(f'        case {name}: return "{name}";')

    out.extend([
        '        default: return "ELOS_UNKNOWN_ERROR";',
        '    }',
        '}',
    ])

    return '\n'.join(out)



def main(args):

    header = f"{ROOT}/include/elos/syscalls.h"
    impl_header = args[1] if len(args) > 1 else f"{ROOT}/include/elos/syscalls_impl.h"


    safe_to_overwrite = False
    if not os.path.exists(impl_header):
        safe_to_overwrite = True
    else:
        with open(impl_header, "r") as f:
            text = f.read()
        if "AUTO-GENERATED" in text:
            safe_to_overwrite = True

    if not safe_to_overwrite:
        print(f"\033[31mERROR:\033[0m {impl_header} is not safe to overwrite.")
        exit(1)

    
    functions = []

    with open(header) as f:
        text = f.read()

    # Remove C block comments
    text = re.sub(r'/\*.*?\*/', '', text, flags=re.S)

    # Remove C++ style comments
    source_text = re.sub(r'//.*', '', text)

    prototypes = prototype_re.findall(source_text)


    for ret, name, args in prototypes:
        ret = " ".join(ret.split())

        arg_list = [ arg_type_name(a) for a in split_args(args) ]
        arg_types = [ a[0] for a in arg_list]
        arg_names = [ a[1] for a in arg_list]

        functions.append((ret, name, arg_types, arg_names))

    output = f'''
/*
    AUTO-GENERATED by {__file__}
*/
    '''
    
    # syscalls_impl.h will almost always only be included by elos/syscalls.
    # But to prevent errors from text editors we include it here.

    output += '''
    
#ifndef ELOS_SYSCALL_INCLUDE
#include "elos/syscalls.h"
#endif // ELOS_SYSCALL_INCLUDE

#ifndef ELOS_SYSCALL_IDS_INCLUDE
#define ELOS_SYSCALL_IDS_INCLUDE
typedef enum {
'''

    for i, (_, name, _, _) in enumerate(functions):
        enum_name = "_SYS_" + name[4:].upper()
        output += f"    {enum_name} = {i},\n"

    output += '''} ELOS_SyscallID;
    
#endif // ELOS_SYSCALL_IDS_INCLUDE
    '''

    output += '''

#ifdef ELOS_SYSCALL_IMPL
#undef ELOS_SYSCALL_IMPL
    '''


    for ret, name, arg_types, arg_names in functions:

        output += f"{ret} {name}("
        output += ", ".join([ arg_types[i] + " " + arg_names[i] for i in range(len(arg_types))])
        output += ")\n{\n"

        if ret != "void":
            output += f"    {ret} retv;\n"
        else:
            output += f"    int retv;\n"

        enum_name = "_SYS_" + name[4:].upper()

        arg_len = len(arg_types)


        #######################
        #    x86 64-bit ABI
        #######################
        output += "#if defined(__x86_64__)\n"
        

        reg_list = [ "rdi", "rsi", "rdx", "r10", "r8", "r9" ]
        for i in range(arg_len):
            output += f'register size_t _arg{i} asm ("{reg_list[i]}") = (size_t){arg_names[i]};\n'

        input_list = ", ".join( [f'"a" ({enum_name})'] + [ f'"r" (_arg{i})' for i in range(arg_len) ])

        output += f'''
            asm volatile (
                "syscall"
                : "=a" (retv)
                : {input_list}
                : "rcx", "r11", "memory"
            );
        '''

        
        #######################
        #    x86 32-bit ABI
        #######################
        output += "#else\n" 

        reg_list = [ "ebx", "ecx", "edx", "esi", "edi", "ebp" ]
        for i in range(arg_len):
            output += f'register size_t _arg{i} asm ("{reg_list[i]}") = (size_t){arg_names[i]};\n'

            if "u64" == arg_types[i].strip():
                print(f"\033[33mWARNING:\033[0m {name} {arg_types[i]} {arg_names[i]}, 64-bit type in 32-bit ABI is not handled.")

        input_list = ", ".join( [f'"a" ({enum_name})'] + [ f'"r" (_arg{i})' for i in range(arg_len) ])

        output += f'''
            asm volatile (
                "int $0x80"
                : "=a" (retv)
                : {input_list}
                : "memory"
            );
        '''


        output += "#endif\n"

        if ret != "void":
            output += "    return retv;\n"

        output += "}\n\n"


    output += '''
#endif // ELOS_SYSCALL_IMPL
    '''


    output += '''
#ifdef ELOS_ERROR_STRING_IMPL
#undef ELOS_ERROR_STRING_IMPL
    '''
    output += generate_error_string(source_text)
    
    output += '''
#endif // ELOS_ERROR_STRING_IMPL
    '''

    with open(impl_header, "w") as f:
        f.write(output)



def split_args(arg_string):
    arg_string = arg_string.strip()

    if not arg_string or arg_string == "void":
        return []

    args = []
    depth = 0
    current = ""

    for c in arg_string:
        if c == ',' and depth == 0:
            args.append(current.strip())
            current = ""
            continue

        if c == '(':
            depth += 1
        elif c == ')':
            depth -= 1

        current += c

    if current.strip():
        args.append(current.strip())

    return args


def arg_type_name(arg):
    arg = arg.strip()

    if arg == "void":
        return None

    # Remove array suffixes
    # syscall signatures don't use arrays
    # arg = re.sub(r'\[[^\]]*\]', '', arg)

    # The last identifier is the variable name
    m = re.search(r'([A-Za-z_][A-Za-z0-9_]*)\s*$', arg)

    if not m:
        raise RuntimeError(f"Couldn't determine argument name: {arg}")
    
    return arg[:m.span()[0]].strip(), m.group(1)


if __name__ == "__main__":
    main(sys.argv)