#!/usr/bin/env python3

import os, sys, re

ROOT = os.path.dirname(__file__)



prototype_re = re.compile(
    r'([A-Za-z_][A-Za-z0-9_\s\*\t]*?)\s+'
    r'(SYS_[A-Za-z0-9_]+)\s*'
    r'\((.*?)\)\s*;',
    re.S
)

error_re = re.compile(
    r'([A-Za-z_][A-Za-z0-9_\s\*\t]*?)\s+'
    r'(SYS_[A-Za-z0-9_]+)\s*'
    r'\((.*?)\)\s*;',
    re.S
)




def generate_error_string(source):
    match = re.search(
        r'typedef\s+enum\s*\{(.*?)\}\s*ELOS_Error\s*;',
        source,
        re.DOTALL,
    )

    if not match:
        print("\033[31mERROR:\033[0m ELOS_Error enum not found")
        raise ValueError()

    entries = []

    for entry in match.group(1).split(','):
        entry = re.sub(r'/\*.*?\*/', '', entry, flags=re.DOTALL)
        entry = re.sub(r'//.*', '', entry).strip()

        if not entry:
            continue

        m = re.match(
            r'^(ELOS_(?:ERR_[A-Za-z0-9_]+|OK))'
            r'(?:\s*=\s*[^,]+)?$',
            entry,
        )

        if m:
            entries.append(m.group(1))

    out = [
        'const char *elos_error(ELOS_Error err) {',
        '    switch (err) {',
    ]

    for name in entries:
        out.append(f'        case {name}: return "{name}";')

    out.extend([
        '        default: return "ELOS_UNKNOWN_ERROR";',
        '    }',
        '}',
    ])

    return '\n'.join(out)



def main(args):

    header = f"{ROOT}/include/elos/syscalls.h"
    impl_header = args[1] if len(args) > 1 else f"{ROOT}/include/elos/syscalls_impl.h"


    safe_to_overwrite = False
    if not os.path.exists(impl_header):
        safe_to_overwrite = True
    else:
        with open(impl_header, "r") as f:
            text = f.read()
        if "AUTO-GENERATED" in text:
            safe_to_overwrite = True

    if not safe_to_overwrite:
        print(f"\033[31mERROR:\033[0m {impl_header} is not safe to overwrite.")
        exit(1)

    
    functions = []

    with open(header) as f:
        text = f.read()

    # Remove C block comments
    text = re.sub(r'/\*.*?\*/', '', text, flags=re.S)

    # Remove C++ style comments
    source_text = re.sub(r'//.*', '', text)

    prototypes = prototype_re.findall(source_text)


    for ret, name, args in prototypes:
        ret = " ".join(ret.split())

        arg_list = split_args(args)
        arg_names = [arg_name(a) for a in arg_list]

        functions.append((ret, name, arg_list, arg_names))

    output = f'''
/*
    AUTO-GENERATED by {__file__}
*/
    '''
    
    # syscalls_impl.h will almost always only be included by elos/syscalls.
    # But to prevent errors from text editors we include it here.

    output += '''
    
#ifndef ELOS_SYSCALL_INCLUDE
#include "elos/syscalls.h"
#endif // ELOS_SYSCALL_INCLUDE

#ifndef ELOS_SYSCALL_IDS_INCLUDE
#define ELOS_SYSCALL_IDS_INCLUDE
typedef enum {
'''

    for i, (_, name, _, _) in enumerate(functions):
        enum_name = "_SYS_" + name[4:].upper()
        output += f"    {enum_name} = {i},\n"

    output += '''} ELOS_SyscallID;
    
#endif // ELOS_SYSCALL_IDS_INCLUDE
    '''


    output += '''

#ifdef ELOS_SYSCALL_IMPL
#undef ELOS_SYSCALL_IMPL

#define SYSCALL0(ID)              \\
    asm volatile (                \\
        "syscall"                 \\
        : "=a" (rax)              \\
        : "a" (ID)                \\
        : "rcx", "r11", "memory"  \\
    );

#define SYSCALL1(ID, ARG0)        \\
    asm volatile (                \\
        "syscall"                 \\
        : "=a" (rax)              \\
        : "a" (ID), "D" (ARG0)    \\
        : "rcx", "r11", "memory"  \\
    );

#define SYSCALL2(ID, ARG0, ARG1)            \\
    asm volatile (                          \\
        "syscall"                           \\
        : "=a" (rax)                        \\
        : "a" (ID), "D" (ARG0), "S" (ARG1)  \\
        : "rcx", "r11", "memory"            \\
    );
    
#define SYSCALL3(ID, ARG0, ARG1, ARG2)                  \\
    asm volatile (                                      \\
        "syscall"                                       \\
        : "=a" (rax)                                    \\
        : "a" (ID), "D" (ARG0), "S" (ARG1), "d" (ARG2)  \\
        : "rcx", "r11", "memory"                        \\
    )

#define SYSCALL4(ID, ARG0, ARG1, ARG2, ARG3)                       \\
    register u64 r10 asm ("r10") = (u64)(ARG3);                    \\
    asm volatile (                                                 \\
        "syscall"                                                  \\
        : "=a" (rax)                                               \\
        : "a" (ID), "D" (ARG0), "S" (ARG1), "d" (ARG2), "r" (r10)  \\
        : "rcx", "r11", "memory"                                   \\
    )

#define SYSCALL5(ID, ARG0, ARG1, ARG2, ARG3, ARG4)                            \\
    register u64 r10 asm ("r10") = (u64)(ARG3);                               \\
    register u64 r8 asm ("r8") = (u64)(ARG4);                                 \\
    asm volatile (                                                            \\
        "syscall"                                                             \\
        : "=a" (rax)                                                          \\
        : "a" (ID), "D" (ARG0), "S" (ARG1), "d" (ARG2), "r" (r10), "r" (r8)   \\
        : "rcx", "r11", "memory"                                              \\
    )

    '''


    for ret, name, arg_list, arg_names in functions:

        output += f"{ret} {name}("
        output += ", ".join(arg_list)
        output += ")\n{\n"

        if ret != "void":
            output += f"    {ret} rax;\n"
        else:
            output += f"    int rax;\n"

        enum_name = "_SYS_" + name[4:].upper()

        argc = len(arg_list)

        if argc == 0:
            output += f"    SYSCALL0({enum_name});\n"
        else:
            output += (
                f"    SYSCALL{argc}({enum_name}, "
                + ", ".join(arg_names)
                + ");\n"
            )

        if ret != "void":
            output += "    return rax;\n"

        output += "}\n\n"


    output += '''
#endif // ELOS_SYSCALL_IMPL
    '''


    output += '''
#ifdef ELOS_ERROR_STRING_IMPL
#undef ELOS_ERROR_STRING_IMPL
    '''
    output += generate_error_string(source_text)
    
    output += '''
#endif // ELOS_ERROR_STRING_IMPL
    '''

    with open(impl_header, "w") as f:
        f.write(output)



def split_args(arg_string):
    arg_string = arg_string.strip()

    if not arg_string or arg_string == "void":
        return []

    args = []
    depth = 0
    current = ""

    for c in arg_string:
        if c == ',' and depth == 0:
            args.append(current.strip())
            current = ""
            continue

        if c == '(':
            depth += 1
        elif c == ')':
            depth -= 1

        current += c

    if current.strip():
        args.append(current.strip())

    return args


def arg_name(arg):
    arg = arg.strip()

    if arg == "void":
        return None

    # Remove array suffixes
    arg = re.sub(r'\[[^\]]*\]', '', arg)

    # The last identifier is the variable name
    m = re.search(r'([A-Za-z_][A-Za-z0-9_]*)\s*$', arg)

    if not m:
        raise RuntimeError(f"Couldn't determine argument name: {arg}")

    return m.group(1)


if __name__ == "__main__":
    main(sys.argv)