
/*
    AUTO-GENERATED by /home/emarioo/dev/elos/kernel/gen_syscalls.py
*/
    
    
#ifndef ELOS_SYSCALL_INCLUDE
#include "elos/elos.h"
#endif // ELOS_SYSCALL_INCLUDE

#ifndef ELOS_SYSCALL_IDS_INCLUDE
#define ELOS_SYSCALL_IDS_INCLUDE
typedef enum ELOS_SyscallID ELOS_SyscallID;
enum ELOS_SyscallID {
    _SYS_PERMISSIONS = 0,
    _SYS_REQUEST_PERMISSIONS = 1,
    _SYS_DEBUG_LOG = 2,
    _SYS_SYSTEM_OPERATION = 3,
    _SYS_HEAP_ALLOCATE = 4,
    _SYS_HEAP_FREE = 5,
    _SYS_HEAP_REALLOCATE = 6,
    _SYS_HEAP_MAP = 7,
    _SYS_HEAP_PROTECT = 8,
    _SYS_DEFAULT_MONITOR = 9,
    _SYS_TICKS_PER_SECOND = 10,
    _SYS_SLEEP_NS = 11,
    _SYS_SHARED_MEMORY_CREATE = 12,
    _SYS_SHARED_MEMORY_GRANT = 13,
    _SYS_SHARED_MEMORY_INFO = 14,
    _SYS_REQUEST_USER_EVENT_BUFFER = 15,
    _SYS_EXIT = 16,
    _SYS_EXIT_THREAD = 17,
    _SYS_SPAWN_THREAD = 18,
    _SYS_JOIN_THREAD = 19,
    _SYS_THREAD_ID = 20,
    _SYS_SPAWN_PROCESS = 21,
    _SYS_KILL_PROCESS = 22,
    _SYS_KILL_PROCESS_BY_NAME = 23,
    _SYS_PROCESS_ID = 24,
    _SYS_DEFAULT_AUDIO = 25,
    _SYS_AUDIO_INFO = 26,
    _SYS_CREATE_AUDIO_BUFFER = 27,
    _SYS_DESTROY_AUDIO_BUFFER = 28,
    _SYS_CREATE_ASYNC_RINGS = 29,
    _SYS_DESTROY_ASYNC_RINGS = 30,
    _SYS_SUBMIT_ASYNC_RING = 31,
    _SYS_WAIT_ASYNC_RING = 32,
};
    
#endif // ELOS_SYSCALL_IDS_INCLUDE
    

#ifdef ELOS_SYSCALL_IMPL
#undef ELOS_SYSCALL_IMPL
    void SYS_permissions(ELOS_Permissions* permissions)
{
    int retv;
#if defined(__x86_64__)
register size_t _arg0 asm ("rdi") = (size_t)permissions;

            asm volatile (
                "syscall"
                : "=a" (retv)
                : "a" (_SYS_PERMISSIONS), "r" (_arg0)
                : "rcx", "r11", "memory"
            );
        #else
register size_t _arg0 asm ("ebx") = (size_t)permissions;

            asm volatile (
                "int $0x80"
                : "=a" (retv)
                : "a" (_SYS_PERMISSIONS), "r" (_arg0)
                : "memory"
            );
        #endif
}

void SYS_request_permissions(ELOS_Permissions* permissions)
{
    int retv;
#if defined(__x86_64__)
register size_t _arg0 asm ("rdi") = (size_t)permissions;

            asm volatile (
                "syscall"
                : "=a" (retv)
                : "a" (_SYS_REQUEST_PERMISSIONS), "r" (_arg0)
                : "rcx", "r11", "memory"
            );
        #else
register size_t _arg0 asm ("ebx") = (size_t)permissions;

            asm volatile (
                "int $0x80"
                : "=a" (retv)
                : "a" (_SYS_REQUEST_PERMISSIONS), "r" (_arg0)
                : "memory"
            );
        #endif
}

void SYS_debug_log(const char* text, uint32_t length)
{
    int retv;
#if defined(__x86_64__)
register size_t _arg0 asm ("rdi") = (size_t)text;
register size_t _arg1 asm ("rsi") = (size_t)length;

            asm volatile (
                "syscall"
                : "=a" (retv)
                : "a" (_SYS_DEBUG_LOG), "r" (_arg0), "r" (_arg1)
                : "rcx", "r11", "memory"
            );
        #else
register size_t _arg0 asm ("ebx") = (size_t)text;
register size_t _arg1 asm ("ecx") = (size_t)length;

            asm volatile (
                "int $0x80"
                : "=a" (retv)
                : "a" (_SYS_DEBUG_LOG), "r" (_arg0), "r" (_arg1)
                : "memory"
            );
        #endif
}

ELOS_Error SYS_system_operation(ELOS_System_Operation operation, uint8_t* data, uint32_t size)
{
    ELOS_Error retv;
#if defined(__x86_64__)
register size_t _arg0 asm ("rdi") = (size_t)operation;
register size_t _arg1 asm ("rsi") = (size_t)data;
register size_t _arg2 asm ("rdx") = (size_t)size;

            asm volatile (
                "syscall"
                : "=a" (retv)
                : "a" (_SYS_SYSTEM_OPERATION), "r" (_arg0), "r" (_arg1), "r" (_arg2)
                : "rcx", "r11", "memory"
            );
        #else
register size_t _arg0 asm ("ebx") = (size_t)operation;
register size_t _arg1 asm ("ecx") = (size_t)data;
register size_t _arg2 asm ("edx") = (size_t)size;

            asm volatile (
                "int $0x80"
                : "=a" (retv)
                : "a" (_SYS_SYSTEM_OPERATION), "r" (_arg0), "r" (_arg1), "r" (_arg2)
                : "memory"
            );
        #endif
    return retv;
}

ELOS_Error SYS_heap_allocate(void** newAddress, size_t size)
{
    ELOS_Error retv;
#if defined(__x86_64__)
register size_t _arg0 asm ("rdi") = (size_t)newAddress;
register size_t _arg1 asm ("rsi") = (size_t)size;

            asm volatile (
                "syscall"
                : "=a" (retv)
                : "a" (_SYS_HEAP_ALLOCATE), "r" (_arg0), "r" (_arg1)
                : "rcx", "r11", "memory"
            );
        #else
register size_t _arg0 asm ("ebx") = (size_t)newAddress;
register size_t _arg1 asm ("ecx") = (size_t)size;

            asm volatile (
                "int $0x80"
                : "=a" (retv)
                : "a" (_SYS_HEAP_ALLOCATE), "r" (_arg0), "r" (_arg1)
                : "memory"
            );
        #endif
    return retv;
}

ELOS_Error SYS_heap_free(void* oldAddress)
{
    ELOS_Error retv;
#if defined(__x86_64__)
register size_t _arg0 asm ("rdi") = (size_t)oldAddress;

            asm volatile (
                "syscall"
                : "=a" (retv)
                : "a" (_SYS_HEAP_FREE), "r" (_arg0)
                : "rcx", "r11", "memory"
            );
        #else
register size_t _arg0 asm ("ebx") = (size_t)oldAddress;

            asm volatile (
                "int $0x80"
                : "=a" (retv)
                : "a" (_SYS_HEAP_FREE), "r" (_arg0)
                : "memory"
            );
        #endif
    return retv;
}

ELOS_Error SYS_heap_reallocate(void** newAddress, size_t size, void* oldAddress)
{
    ELOS_Error retv;
#if defined(__x86_64__)
register size_t _arg0 asm ("rdi") = (size_t)newAddress;
register size_t _arg1 asm ("rsi") = (size_t)size;
register size_t _arg2 asm ("rdx") = (size_t)oldAddress;

            asm volatile (
                "syscall"
                : "=a" (retv)
                : "a" (_SYS_HEAP_REALLOCATE), "r" (_arg0), "r" (_arg1), "r" (_arg2)
                : "rcx", "r11", "memory"
            );
        #else
register size_t _arg0 asm ("ebx") = (size_t)newAddress;
register size_t _arg1 asm ("ecx") = (size_t)size;
register size_t _arg2 asm ("edx") = (size_t)oldAddress;

            asm volatile (
                "int $0x80"
                : "=a" (retv)
                : "a" (_SYS_HEAP_REALLOCATE), "r" (_arg0), "r" (_arg1), "r" (_arg2)
                : "memory"
            );
        #endif
    return retv;
}

ELOS_Error SYS_heap_map(void* virtAddress, size_t size, ELOS_Heap_Protection protection)
{
    ELOS_Error retv;
#if defined(__x86_64__)
register size_t _arg0 asm ("rdi") = (size_t)virtAddress;
register size_t _arg1 asm ("rsi") = (size_t)size;
register size_t _arg2 asm ("rdx") = (size_t)protection;

            asm volatile (
                "syscall"
                : "=a" (retv)
                : "a" (_SYS_HEAP_MAP), "r" (_arg0), "r" (_arg1), "r" (_arg2)
                : "rcx", "r11", "memory"
            );
        #else
register size_t _arg0 asm ("ebx") = (size_t)virtAddress;
register size_t _arg1 asm ("ecx") = (size_t)size;
register size_t _arg2 asm ("edx") = (size_t)protection;

            asm volatile (
                "int $0x80"
                : "=a" (retv)
                : "a" (_SYS_HEAP_MAP), "r" (_arg0), "r" (_arg1), "r" (_arg2)
                : "memory"
            );
        #endif
    return retv;
}

ELOS_Error SYS_heap_protect(void* virtAddress, size_t size, ELOS_Heap_Protection protection)
{
    ELOS_Error retv;
#if defined(__x86_64__)
register size_t _arg0 asm ("rdi") = (size_t)virtAddress;
register size_t _arg1 asm ("rsi") = (size_t)size;
register size_t _arg2 asm ("rdx") = (size_t)protection;

            asm volatile (
                "syscall"
                : "=a" (retv)
                : "a" (_SYS_HEAP_PROTECT), "r" (_arg0), "r" (_arg1), "r" (_arg2)
                : "rcx", "r11", "memory"
            );
        #else
register size_t _arg0 asm ("ebx") = (size_t)virtAddress;
register size_t _arg1 asm ("ecx") = (size_t)size;
register size_t _arg2 asm ("edx") = (size_t)protection;

            asm volatile (
                "int $0x80"
                : "=a" (retv)
                : "a" (_SYS_HEAP_PROTECT), "r" (_arg0), "r" (_arg1), "r" (_arg2)
                : "memory"
            );
        #endif
    return retv;
}

ELOS_Error SYS_default_monitor(ELOS_FrameBuffer* frameBuffer)
{
    ELOS_Error retv;
#if defined(__x86_64__)
register size_t _arg0 asm ("rdi") = (size_t)frameBuffer;

            asm volatile (
                "syscall"
                : "=a" (retv)
                : "a" (_SYS_DEFAULT_MONITOR), "r" (_arg0)
                : "rcx", "r11", "memory"
            );
        #else
register size_t _arg0 asm ("ebx") = (size_t)frameBuffer;

            asm volatile (
                "int $0x80"
                : "=a" (retv)
                : "a" (_SYS_DEFAULT_MONITOR), "r" (_arg0)
                : "memory"
            );
        #endif
    return retv;
}

ELOS_Error SYS_ticks_per_second(uint64_t* tps)
{
    ELOS_Error retv;
#if defined(__x86_64__)
register size_t _arg0 asm ("rdi") = (size_t)tps;

            asm volatile (
                "syscall"
                : "=a" (retv)
                : "a" (_SYS_TICKS_PER_SECOND), "r" (_arg0)
                : "rcx", "r11", "memory"
            );
        #else
register size_t _arg0 asm ("ebx") = (size_t)tps;

            asm volatile (
                "int $0x80"
                : "=a" (retv)
                : "a" (_SYS_TICKS_PER_SECOND), "r" (_arg0)
                : "memory"
            );
        #endif
    return retv;
}

void SYS_sleep_ns(uint64_t nanoseconds)
{
    int retv;
#if defined(__x86_64__)
register size_t _arg0 asm ("rdi") = (size_t)nanoseconds;

            asm volatile (
                "syscall"
                : "=a" (retv)
                : "a" (_SYS_SLEEP_NS), "r" (_arg0)
                : "rcx", "r11", "memory"
            );
        #else
register size_t _arg0 asm ("ebx") = (size_t)nanoseconds;

            asm volatile (
                "int $0x80"
                : "=a" (retv)
                : "a" (_SYS_SLEEP_NS), "r" (_arg0)
                : "memory"
            );
        #endif
}

ELOS_Error SYS_shared_memory_create(size_t size, ELOS_SharedMemoryHandle* handle)
{
    ELOS_Error retv;
#if defined(__x86_64__)
register size_t _arg0 asm ("rdi") = (size_t)size;
register size_t _arg1 asm ("rsi") = (size_t)handle;

            asm volatile (
                "syscall"
                : "=a" (retv)
                : "a" (_SYS_SHARED_MEMORY_CREATE), "r" (_arg0), "r" (_arg1)
                : "rcx", "r11", "memory"
            );
        #else
register size_t _arg0 asm ("ebx") = (size_t)size;
register size_t _arg1 asm ("ecx") = (size_t)handle;

            asm volatile (
                "int $0x80"
                : "=a" (retv)
                : "a" (_SYS_SHARED_MEMORY_CREATE), "r" (_arg0), "r" (_arg1)
                : "memory"
            );
        #endif
    return retv;
}

ELOS_Error SYS_shared_memory_grant(ELOS_SharedMemoryHandle handle, ELOS_ProcessID processID)
{
    ELOS_Error retv;
#if defined(__x86_64__)
register size_t _arg0 asm ("rdi") = (size_t)handle;
register size_t _arg1 asm ("rsi") = (size_t)processID;

            asm volatile (
                "syscall"
                : "=a" (retv)
                : "a" (_SYS_SHARED_MEMORY_GRANT), "r" (_arg0), "r" (_arg1)
                : "rcx", "r11", "memory"
            );
        #else
register size_t _arg0 asm ("ebx") = (size_t)handle;
register size_t _arg1 asm ("ecx") = (size_t)processID;

            asm volatile (
                "int $0x80"
                : "=a" (retv)
                : "a" (_SYS_SHARED_MEMORY_GRANT), "r" (_arg0), "r" (_arg1)
                : "memory"
            );
        #endif
    return retv;
}

ELOS_Error SYS_shared_memory_info(ELOS_SharedMemoryHandle handle, void** buffer, size_t* size)
{
    ELOS_Error retv;
#if defined(__x86_64__)
register size_t _arg0 asm ("rdi") = (size_t)handle;
register size_t _arg1 asm ("rsi") = (size_t)buffer;
register size_t _arg2 asm ("rdx") = (size_t)size;

            asm volatile (
                "syscall"
                : "=a" (retv)
                : "a" (_SYS_SHARED_MEMORY_INFO), "r" (_arg0), "r" (_arg1), "r" (_arg2)
                : "rcx", "r11", "memory"
            );
        #else
register size_t _arg0 asm ("ebx") = (size_t)handle;
register size_t _arg1 asm ("ecx") = (size_t)buffer;
register size_t _arg2 asm ("edx") = (size_t)size;

            asm volatile (
                "int $0x80"
                : "=a" (retv)
                : "a" (_SYS_SHARED_MEMORY_INFO), "r" (_arg0), "r" (_arg1), "r" (_arg2)
                : "memory"
            );
        #endif
    return retv;
}

ELOS_Error SYS_request_user_event_buffer(uint32_t minimumEvents, ELOS_UserEventBuffer** buffer)
{
    ELOS_Error retv;
#if defined(__x86_64__)
register size_t _arg0 asm ("rdi") = (size_t)minimumEvents;
register size_t _arg1 asm ("rsi") = (size_t)buffer;

            asm volatile (
                "syscall"
                : "=a" (retv)
                : "a" (_SYS_REQUEST_USER_EVENT_BUFFER), "r" (_arg0), "r" (_arg1)
                : "rcx", "r11", "memory"
            );
        #else
register size_t _arg0 asm ("ebx") = (size_t)minimumEvents;
register size_t _arg1 asm ("ecx") = (size_t)buffer;

            asm volatile (
                "int $0x80"
                : "=a" (retv)
                : "a" (_SYS_REQUEST_USER_EVENT_BUFFER), "r" (_arg0), "r" (_arg1)
                : "memory"
            );
        #endif
    return retv;
}

void SYS_exit(int exitCode)
{
    int retv;
#if defined(__x86_64__)
register size_t _arg0 asm ("rdi") = (size_t)exitCode;

            asm volatile (
                "syscall"
                : "=a" (retv)
                : "a" (_SYS_EXIT), "r" (_arg0)
                : "rcx", "r11", "memory"
            );
        #else
register size_t _arg0 asm ("ebx") = (size_t)exitCode;

            asm volatile (
                "int $0x80"
                : "=a" (retv)
                : "a" (_SYS_EXIT), "r" (_arg0)
                : "memory"
            );
        #endif
}

void SYS_exit_thread()
{
    int retv;
#if defined(__x86_64__)

            asm volatile (
                "syscall"
                : "=a" (retv)
                : "a" (_SYS_EXIT_THREAD)
                : "rcx", "r11", "memory"
            );
        #else

            asm volatile (
                "int $0x80"
                : "=a" (retv)
                : "a" (_SYS_EXIT_THREAD)
                : "memory"
            );
        #endif
}

ELOS_Error SYS_spawn_thread(FN_thread_entry entry, ELOS_ThreadHandle* handle)
{
    ELOS_Error retv;
#if defined(__x86_64__)
register size_t _arg0 asm ("rdi") = (size_t)entry;
register size_t _arg1 asm ("rsi") = (size_t)handle;

            asm volatile (
                "syscall"
                : "=a" (retv)
                : "a" (_SYS_SPAWN_THREAD), "r" (_arg0), "r" (_arg1)
                : "rcx", "r11", "memory"
            );
        #else
register size_t _arg0 asm ("ebx") = (size_t)entry;
register size_t _arg1 asm ("ecx") = (size_t)handle;

            asm volatile (
                "int $0x80"
                : "=a" (retv)
                : "a" (_SYS_SPAWN_THREAD), "r" (_arg0), "r" (_arg1)
                : "memory"
            );
        #endif
    return retv;
}

ELOS_Error SYS_join_thread(ELOS_ThreadHandle handle)
{
    ELOS_Error retv;
#if defined(__x86_64__)
register size_t _arg0 asm ("rdi") = (size_t)handle;

            asm volatile (
                "syscall"
                : "=a" (retv)
                : "a" (_SYS_JOIN_THREAD), "r" (_arg0)
                : "rcx", "r11", "memory"
            );
        #else
register size_t _arg0 asm ("ebx") = (size_t)handle;

            asm volatile (
                "int $0x80"
                : "=a" (retv)
                : "a" (_SYS_JOIN_THREAD), "r" (_arg0)
                : "memory"
            );
        #endif
    return retv;
}

ELOS_ThreadID SYS_thread_id(ELOS_ThreadHandle handle)
{
    ELOS_ThreadID retv;
#if defined(__x86_64__)
register size_t _arg0 asm ("rdi") = (size_t)handle;

            asm volatile (
                "syscall"
                : "=a" (retv)
                : "a" (_SYS_THREAD_ID), "r" (_arg0)
                : "rcx", "r11", "memory"
            );
        #else
register size_t _arg0 asm ("ebx") = (size_t)handle;

            asm volatile (
                "int $0x80"
                : "=a" (retv)
                : "a" (_SYS_THREAD_ID), "r" (_arg0)
                : "memory"
            );
        #endif
    return retv;
}

ELOS_Error SYS_spawn_process(const char* path, const char* data, uint32_t data_len, ELOS_ProcessHandle* handle)
{
    ELOS_Error retv;
#if defined(__x86_64__)
register size_t _arg0 asm ("rdi") = (size_t)path;
register size_t _arg1 asm ("rsi") = (size_t)data;
register size_t _arg2 asm ("rdx") = (size_t)data_len;
register size_t _arg3 asm ("r10") = (size_t)handle;

            asm volatile (
                "syscall"
                : "=a" (retv)
                : "a" (_SYS_SPAWN_PROCESS), "r" (_arg0), "r" (_arg1), "r" (_arg2), "r" (_arg3)
                : "rcx", "r11", "memory"
            );
        #else
register size_t _arg0 asm ("ebx") = (size_t)path;
register size_t _arg1 asm ("ecx") = (size_t)data;
register size_t _arg2 asm ("edx") = (size_t)data_len;
register size_t _arg3 asm ("esi") = (size_t)handle;

            asm volatile (
                "int $0x80"
                : "=a" (retv)
                : "a" (_SYS_SPAWN_PROCESS), "r" (_arg0), "r" (_arg1), "r" (_arg2), "r" (_arg3)
                : "memory"
            );
        #endif
    return retv;
}

ELOS_Error SYS_kill_process(ELOS_ProcessHandle handle)
{
    ELOS_Error retv;
#if defined(__x86_64__)
register size_t _arg0 asm ("rdi") = (size_t)handle;

            asm volatile (
                "syscall"
                : "=a" (retv)
                : "a" (_SYS_KILL_PROCESS), "r" (_arg0)
                : "rcx", "r11", "memory"
            );
        #else
register size_t _arg0 asm ("ebx") = (size_t)handle;

            asm volatile (
                "int $0x80"
                : "=a" (retv)
                : "a" (_SYS_KILL_PROCESS), "r" (_arg0)
                : "memory"
            );
        #endif
    return retv;
}

ELOS_Error SYS_kill_process_by_name(const char* name)
{
    ELOS_Error retv;
#if defined(__x86_64__)
register size_t _arg0 asm ("rdi") = (size_t)name;

            asm volatile (
                "syscall"
                : "=a" (retv)
                : "a" (_SYS_KILL_PROCESS_BY_NAME), "r" (_arg0)
                : "rcx", "r11", "memory"
            );
        #else
register size_t _arg0 asm ("ebx") = (size_t)name;

            asm volatile (
                "int $0x80"
                : "=a" (retv)
                : "a" (_SYS_KILL_PROCESS_BY_NAME), "r" (_arg0)
                : "memory"
            );
        #endif
    return retv;
}

ELOS_ProcessID SYS_process_id()
{
    ELOS_ProcessID retv;
#if defined(__x86_64__)

            asm volatile (
                "syscall"
                : "=a" (retv)
                : "a" (_SYS_PROCESS_ID)
                : "rcx", "r11", "memory"
            );
        #else

            asm volatile (
                "int $0x80"
                : "=a" (retv)
                : "a" (_SYS_PROCESS_ID)
                : "memory"
            );
        #endif
    return retv;
}

ELOS_Error SYS_default_audio(ELOS_AudioDevice* device)
{
    ELOS_Error retv;
#if defined(__x86_64__)
register size_t _arg0 asm ("rdi") = (size_t)device;

            asm volatile (
                "syscall"
                : "=a" (retv)
                : "a" (_SYS_DEFAULT_AUDIO), "r" (_arg0)
                : "rcx", "r11", "memory"
            );
        #else
register size_t _arg0 asm ("ebx") = (size_t)device;

            asm volatile (
                "int $0x80"
                : "=a" (retv)
                : "a" (_SYS_DEFAULT_AUDIO), "r" (_arg0)
                : "memory"
            );
        #endif
    return retv;
}

ELOS_Error SYS_audio_info(ELOS_AudioDevice device, ELOS_AudioDeviceInfo* info)
{
    ELOS_Error retv;
#if defined(__x86_64__)
register size_t _arg0 asm ("rdi") = (size_t)device;
register size_t _arg1 asm ("rsi") = (size_t)info;

            asm volatile (
                "syscall"
                : "=a" (retv)
                : "a" (_SYS_AUDIO_INFO), "r" (_arg0), "r" (_arg1)
                : "rcx", "r11", "memory"
            );
        #else
register size_t _arg0 asm ("ebx") = (size_t)device;
register size_t _arg1 asm ("ecx") = (size_t)info;

            asm volatile (
                "int $0x80"
                : "=a" (retv)
                : "a" (_SYS_AUDIO_INFO), "r" (_arg0), "r" (_arg1)
                : "memory"
            );
        #endif
    return retv;
}

ELOS_Error SYS_create_audio_buffer(ELOS_AudioDevice device, ELOS_AudioFormat* format, uint32_t bufferSize, ELOS_AudioBuffer** buffer)
{
    ELOS_Error retv;
#if defined(__x86_64__)
register size_t _arg0 asm ("rdi") = (size_t)device;
register size_t _arg1 asm ("rsi") = (size_t)format;
register size_t _arg2 asm ("rdx") = (size_t)bufferSize;
register size_t _arg3 asm ("r10") = (size_t)buffer;

            asm volatile (
                "syscall"
                : "=a" (retv)
                : "a" (_SYS_CREATE_AUDIO_BUFFER), "r" (_arg0), "r" (_arg1), "r" (_arg2), "r" (_arg3)
                : "rcx", "r11", "memory"
            );
        #else
register size_t _arg0 asm ("ebx") = (size_t)device;
register size_t _arg1 asm ("ecx") = (size_t)format;
register size_t _arg2 asm ("edx") = (size_t)bufferSize;
register size_t _arg3 asm ("esi") = (size_t)buffer;

            asm volatile (
                "int $0x80"
                : "=a" (retv)
                : "a" (_SYS_CREATE_AUDIO_BUFFER), "r" (_arg0), "r" (_arg1), "r" (_arg2), "r" (_arg3)
                : "memory"
            );
        #endif
    return retv;
}

ELOS_Error SYS_destroy_audio_buffer(ELOS_AudioDevice device, ELOS_AudioBuffer* buffer)
{
    ELOS_Error retv;
#if defined(__x86_64__)
register size_t _arg0 asm ("rdi") = (size_t)device;
register size_t _arg1 asm ("rsi") = (size_t)buffer;

            asm volatile (
                "syscall"
                : "=a" (retv)
                : "a" (_SYS_DESTROY_AUDIO_BUFFER), "r" (_arg0), "r" (_arg1)
                : "rcx", "r11", "memory"
            );
        #else
register size_t _arg0 asm ("ebx") = (size_t)device;
register size_t _arg1 asm ("ecx") = (size_t)buffer;

            asm volatile (
                "int $0x80"
                : "=a" (retv)
                : "a" (_SYS_DESTROY_AUDIO_BUFFER), "r" (_arg0), "r" (_arg1)
                : "memory"
            );
        #endif
    return retv;
}

ELOS_Error SYS_create_async_rings(uint32_t maxEntries, ELOS_AsyncCreateFlag flags, ELOS_AsyncRequestRing** requestRing, ELOS_AsyncCompletionRing** completionRing)
{
    ELOS_Error retv;
#if defined(__x86_64__)
register size_t _arg0 asm ("rdi") = (size_t)maxEntries;
register size_t _arg1 asm ("rsi") = (size_t)flags;
register size_t _arg2 asm ("rdx") = (size_t)requestRing;
register size_t _arg3 asm ("r10") = (size_t)completionRing;

            asm volatile (
                "syscall"
                : "=a" (retv)
                : "a" (_SYS_CREATE_ASYNC_RINGS), "r" (_arg0), "r" (_arg1), "r" (_arg2), "r" (_arg3)
                : "rcx", "r11", "memory"
            );
        #else
register size_t _arg0 asm ("ebx") = (size_t)maxEntries;
register size_t _arg1 asm ("ecx") = (size_t)flags;
register size_t _arg2 asm ("edx") = (size_t)requestRing;
register size_t _arg3 asm ("esi") = (size_t)completionRing;

            asm volatile (
                "int $0x80"
                : "=a" (retv)
                : "a" (_SYS_CREATE_ASYNC_RINGS), "r" (_arg0), "r" (_arg1), "r" (_arg2), "r" (_arg3)
                : "memory"
            );
        #endif
    return retv;
}

ELOS_Error SYS_destroy_async_rings(ELOS_AsyncRequestRing* requestRing, ELOS_AsyncCompletionRing* completionRing)
{
    ELOS_Error retv;
#if defined(__x86_64__)
register size_t _arg0 asm ("rdi") = (size_t)requestRing;
register size_t _arg1 asm ("rsi") = (size_t)completionRing;

            asm volatile (
                "syscall"
                : "=a" (retv)
                : "a" (_SYS_DESTROY_ASYNC_RINGS), "r" (_arg0), "r" (_arg1)
                : "rcx", "r11", "memory"
            );
        #else
register size_t _arg0 asm ("ebx") = (size_t)requestRing;
register size_t _arg1 asm ("ecx") = (size_t)completionRing;

            asm volatile (
                "int $0x80"
                : "=a" (retv)
                : "a" (_SYS_DESTROY_ASYNC_RINGS), "r" (_arg0), "r" (_arg1)
                : "memory"
            );
        #endif
    return retv;
}

ELOS_Error SYS_submit_async_ring(ELOS_AsyncRequestRing* requestRing)
{
    ELOS_Error retv;
#if defined(__x86_64__)
register size_t _arg0 asm ("rdi") = (size_t)requestRing;

            asm volatile (
                "syscall"
                : "=a" (retv)
                : "a" (_SYS_SUBMIT_ASYNC_RING), "r" (_arg0)
                : "rcx", "r11", "memory"
            );
        #else
register size_t _arg0 asm ("ebx") = (size_t)requestRing;

            asm volatile (
                "int $0x80"
                : "=a" (retv)
                : "a" (_SYS_SUBMIT_ASYNC_RING), "r" (_arg0)
                : "memory"
            );
        #endif
    return retv;
}

ELOS_Error SYS_wait_async_ring(ELOS_AsyncCompletionRing* completionRing, uint64_t timeout_ns)
{
    ELOS_Error retv;
#if defined(__x86_64__)
register size_t _arg0 asm ("rdi") = (size_t)completionRing;
register size_t _arg1 asm ("rsi") = (size_t)timeout_ns;

            asm volatile (
                "syscall"
                : "=a" (retv)
                : "a" (_SYS_WAIT_ASYNC_RING), "r" (_arg0), "r" (_arg1)
                : "rcx", "r11", "memory"
            );
        #else
register size_t _arg0 asm ("ebx") = (size_t)completionRing;
register size_t _arg1 asm ("ecx") = (size_t)timeout_ns;

            asm volatile (
                "int $0x80"
                : "=a" (retv)
                : "a" (_SYS_WAIT_ASYNC_RING), "r" (_arg0), "r" (_arg1)
                : "memory"
            );
        #endif
    return retv;
}


#endif // ELOS_SYSCALL_IMPL
    
#ifdef ELOS_ERROR_STRING_IMPL
#undef ELOS_ERROR_STRING_IMPL
    const char *elos_error(ELOS_Error err) {
    switch (err) {
        case ELOS_OK: return "ELOS_OK";
        case ELOS_ERR_RESERVED: return "ELOS_ERR_RESERVED";
        case ELOS_ERR_UNKNOWN: return "ELOS_ERR_UNKNOWN";
        case ELOS_ERR_INVALID_PARAM: return "ELOS_ERR_INVALID_PARAM";
        case ELOS_ERR_INVALID_SYSCALL: return "ELOS_ERR_INVALID_SYSCALL";
        case ELOS_ERR_PERMISSION_DENIED: return "ELOS_ERR_PERMISSION_DENIED";
        case ELOS_ERR_NOT_FOUND: return "ELOS_ERR_NOT_FOUND";
        case ELOS_ERR_BUSY: return "ELOS_ERR_BUSY";
        case ELOS_ERR_TIMEOUT: return "ELOS_ERR_TIMEOUT";
        case ELOS_ERR_OUT_OF_BOUNDS: return "ELOS_ERR_OUT_OF_BOUNDS";
        case ELOS_ERR_UNSUPPORTED_AUDIO_FORMAT: return "ELOS_ERR_UNSUPPORTED_AUDIO_FORMAT";
        case ELOS_ERR_BUFFER_SIZE_NOT_FRAME_ALIGNED: return "ELOS_ERR_BUFFER_SIZE_NOT_FRAME_ALIGNED";
        case ELOS_ERR_BUFFER_SIZE_TOO_BIG: return "ELOS_ERR_BUFFER_SIZE_TOO_BIG";
        case ELOS_ERR_BUFFER_SIZE_TOO_SMALL: return "ELOS_ERR_BUFFER_SIZE_TOO_SMALL";
        case ELOS_ERR_NO_AUDIO_DEVICE: return "ELOS_ERR_NO_AUDIO_DEVICE";
        default: return "ELOS_UNKNOWN_ERROR";
    }
}
#endif // ELOS_ERROR_STRING_IMPL
    