.intel_syntax noprefix

.section .text

.global __udivdi3
__udivdi3:
    push    ebp
    mov     ebp, esp
    push    ebx
    push    esi
    push    edi
    sub     esp, 28

    # Arguments:
    # [ebp+8]  = numerator low
    # [ebp+12] = numerator high
    # [ebp+16] = denominator low
    # [ebp+20] = denominator high
    #
    # Locals:
    # [ebp-4]  = numerator low
    # [ebp-8]  = numerator high
    # [ebp-12] = remainder low
    # [ebp-16] = remainder high
    # [ebp-20] = quotient low
    # [ebp-24] = quotient high
    # [ebp-28] = counter

    mov     eax, [ebp+8]
    mov     [ebp-4], eax

    mov     eax, [ebp+12]
    mov     [ebp-8], eax

    xor     eax, eax
    mov     [ebp-12], eax       # remainder low
    mov     [ebp-16], eax       # remainder high
    mov     [ebp-20], eax       # quotient low
    mov     [ebp-24], eax       # quotient high

    mov     dword ptr [ebp-28], 64

.loop:
    # Extract the next bit from the MSB of numerator.
    # We shift the 64-bit numerator left.
    #
    # First save the carry generated by the high-word shift.
    mov     eax, [ebp-8]
    shr     eax, 31             # eax = next input bit (0 or 1)

    shl     dword ptr [ebp-4], 1
    shl     dword ptr [ebp-8], 1

    # Remainder <<= 1
    shl     dword ptr [ebp-12], 1
    rcl     dword ptr [ebp-16], 1

    # remainder |= extracted bit
    or      [ebp-12], eax

    # Compare remainder with denominator.
    mov     eax, [ebp-16]
    cmp     eax, [ebp+20]
    jb      .no_subtract
    ja      .subtract

    mov     eax, [ebp-12]
    cmp     eax, [ebp+16]
    jb      .no_subtract

.subtract:
    # remainder -= denominator
    mov     eax, [ebp+16]
    sub     [ebp-12], eax

    mov     eax, [ebp+20]
    sbb     [ebp-16], eax

    # quotient |= 1
    or      dword ptr [ebp-20], 1

.no_subtract:
    # Shift quotient left for the next bit.
    # We need this before the next iteration, but don't shift
    # after the final iteration.
    dec     dword ptr [ebp-28]
    jz      .done

    shl     dword ptr [ebp-20], 1
    rcl     dword ptr [ebp-24], 1

    jmp     .loop

.done:
    mov     eax, [ebp-20]
    mov     edx, [ebp-24]

    add     esp, 28
    pop     edi
    pop     esi
    pop     ebx
    pop     ebp
    ret
